
import React, { createContext, useState, useContext, useEffect } from 'react';
const LanguageContext = createContext();
const translations = {
    en: {
       
        loginPage: {
            title: "Login",
            emailLabel: "Email",
            passwordLabel: "Password",
            loginButton: "Login",
            loginFailed: "Login failed. Please check your credentials.",
             noAccount: "Don't have an account?",
            loggingInButton: "Logging In...",
            signUpLink: " Sign up here",
            loginSuccess: "Login successful!",
        },
        registerPage: {
            title: "Register",
            nameLabel: "Name",
            emailLabel: "Email",
            passwordLabel: "Password",
            confirmPasswordLabel: "Confirm Password",
            registerButton: "Register",
            passwordMismatch: "Passwords do not match",
            registering: "Registering...",
            registrationSuccess: "Registration successful!",
            haveAccount: "Already have an account?",
            loginTitle: "Login",
            registerTitle: "Register",
            alreadyHaveAccount : "Already have an account?",
            signInLink: "Sign In Here",
            submittingButton: "Submit",
        },
        general: {
            loading: "Loading...",
            error: "Error",
            view: "View Product",
            shopNow: "Shop Now",
            errorFetchingProducts: "Failed to load products.",
            errorFetchingOrders: "Failed to fetch orders.",
            errorFetchingUsers: "Failed to fetch users.",
            errorFetchingCategories: "Failed to fetch categories.",
            unnamedProduct: "Unnamed Product",
            total: "Total",
            no : "No",
            yes : "Yes",
            loadingOrders: "Loading orders...",
            errorFetchingData: "Failed to fetch data.",
            verifyHuman: "Please verify you are human.",
        },
        homepage: {
            discountsTitle: "Discounts",
            discountCode: "Discount Code",
          off: "offer",
          validUntil: "Valid Until",
          copyCode: "Copy Code",
          discountCode: "Discount Code",
          copied: "Copied!",



        },
        shopPage: {
            searchProduct: "Search Product",
            searchHere: "Search here...",
            priceRange: "Price Range",
            filterByBrand: "Filter by Brand",
            sortBy: "Sort by:",
            popularity: "Popularity",
            priceLowToHigh: "Price: Low to High",
            priceHighToLow: "Price: High to Low",
            nameAZ: "Name (A-Z)",
            showingItems: "Showing",
            items: "items",
            noProductsFound: "No products found matching your criteria.",
            addToCart: "Add to Cart",
            removeFromCart: "Remove from Cart",
            addToFavorites: "Add to Favorites",
            removeFromFavorites: "Remove from Favorites",
            currencySymbol: "$",
            filter: "Filter",
            showFilters: "Show Filters",
            locale: 'en-US',
        },
        productDetailsPage: {
            quantity: "Quantity",
            securePayment: "Secure Payment",
            fastShipping: "Fast Shipping",
            qualityGuarantee: "Quality Guarantee",
            productDescription: "Product Description",
            pleaseLoginToAddFavorites: "Please log in to add to favorites.",
            pleaseLoginToAddCart: "Please log in to add to cart.",
        },
        cartPage: {
            shoppingCart: "Shopping Cart",
            cartEmpty: "Your cart is empty.",
            cartEmptyDesc: "Looks like you haven't added anything to your cart yet.",
            continueShopping: "Continue Shopping",
            removeItem: "Remove Item",
            cartTotal: "Cart Total",
            proceedToCheckout: "Proceed to Checkout",
            loadingCart: "Loading cart...",
            cartEmptyCheckout: "Your cart is empty. Add items before checking out.",
            cartEmptyCheckoutRedirect: "Your cart is empty. Redirecting to shop...",
            decreaseQuantity: "Decrease quantity",
            increaseQuantity: "Increase quantity",
            productQuantity: "Product quantity",
        },
        checkoutPage: {
            checkout: "Checkout",
            orderSummary: "Order Summary",
            shippingAndPayment: "Shipping & Payment",
            shippingAddress: "Shipping Address",
            paymentMethod: "Payment Method",
            placeOrder: "Place Order",
            placingOrder: "Placing Order...",
            orderPlacedSuccessTitle: "Order Placed Successfully!",
            orderPlacedSuccessMessage: "Thank you for your purchase. You will be redirected to the home page shortly.",
            redirecting: "Redirecting...",
            orderPlacementFailed: "Order placement failed.",
            orderPlacementError: "Error placing order",
            pleaseLoginToCheckout: "Please log in to checkout.",
            shippingPaymentRequired: "Please provide shipping address and payment method.",
            checkoutPlaceholder: "Proceeding to checkout...",
            placeOrderPlaceholder: "Placing order... (Backend logic needed)",
            enterAddressPlaceholder: "Enter Address",
            enterCityPlaceholder: "Enter City",
            enterPostalCodePlaceholder: "Enter Postal Code",
            enterCountryPlaceholder: "Enter Country",
            cashOnDelivery: "Cash on Delivery",
            checkoutTitle: "Checkout",
            selectPaymentMethod: "Select Payment Method",
            selectShippingAddress: "Select Shipping Address",
        },
        adminOrdersPage: {
            allOrders: "All Orders",
            orderID: "Order ID",
            user: "User",
            date: "Date",
            paid: "Paid",
            delivered: "Delivered",
            details: "Details",
            loadingOrders: "Loading orders...",
            errorFetchingOrders: "Failed to fetch orders.",
            noOrdersFound: "No orders found.",
            yes: "Yes",
            no: "No",
            orderDetails: "Order Details",
            shippingAddress: "Shipping Address",
            address: "Address",
            status: "Status",
            notDelivered: "Not Delivered",
            markAsDelivered: "Mark as Delivered",
            customerInfo: "Customer Info",
            name: "Name",
            email: "Email",
            paymentMethod: "Payment Method",
            method: "Method",
            notPaid: "Not Paid",
            markAsPaid: "Mark as Paid",
            orderSummary: "Order Summary",
            itemsPrice: "Items Price",
            shippingPrice: "Shipping Price",
            taxPrice: "Tax Price",
            totalPrice: "Total Price",
            orderItems: "Order Items",
            dates: "Dates",
            orderedAt: "Ordered At",
        },
        heroSection: {
            bigSale: "Big Sale",
            comboOffer: "Combo Offer",
            installment: "Installment available",
            weeklySale: "Weekly Sale",
            weeklyDesc: "Don't miss our amazing weekly offers! Up to",
            off: "OFF",
            thisWeek: "this week.",
            languageArabic: "العربية",
            languageEnglish: "English",
            lightMode: "Light Mode",
            darkMode: "Dark Mode",
        },
        heroSlidesData: [
             {
                image: require("../Assets/hero5.png"),
                title: "Ultimate Security Pack",
                desc: "High-end surveillance cameras with remote access.",
                price: "EGP 28,320.00",
            },
            {
                image: require("../Assets/hero2.png"),
                title: "Smart Home Bundle",
                desc: "Control your home from your phone.",
                price: "EGP 14,200.00",
            },
            {
                image: require("../Assets/hero3.jpg"),
                title: "Office Camera Kit",
                desc: "Secure your business with smart AI detection.",
                price: "EGP 17,990.00",
            },
            {
                image: require("../Assets/hero6.png"),
                title: "Outdoor Cam Pro",
                desc: "Weather-proof, night vision, and more.",
                price: "EGP 9,500.00",
            },
        ],
        heroSideOffers: {
            iphoneOffer: {
                productName: "iPhone 12 Pro Max",
                price: "EGP 12,480.00",
                image: "/Assets/hero5.png", 
            },
        },
        categories: {
            "All Categories": "All Categories",
            Watch: "Watch",
            Speaker: "Speaker",
            Camera: "Camera",
            Phone: "Phone",
            Headphone: "Headphone",
            Laptop: "Laptop",
            TV: "TV",
        },
        brands: {
            "All Brands": "All Brands",
        },
        topBar: {
            currency: "Currency",
            language: "Language",
            home: "Home",
            shop: "Shop",
            aboutUs: "About Us",
            contactUs: "Contact Us",
            dashboard: "Dashboard",
            logout: "Logout",
            helloGuest: "Hello, Guest",
            signIn: "Sign In",
            register: "Register",
            light: "Light",
            dark: "Dark",
            helloUser: "Hello",
            languageArabic: "العربية",
            languageEnglish: "English",
            lightMode: "Light Mode",
            darkMode: "Dark Mode",
        },
        mainHeader: {
            siteName: "TechXpress",
            searchPlaceholder: "Search for products...",
            allCategories: "All",
            hotline: "Hotline",
            myWishlist: "My Wishlist",
            myCart: "My Cart",
            searchError: "An error occurred during search.",
        },
        contactUsPage: {
            title: 'Contact Us',
            description: 'Have any questions or need assistance? Feel free to reach out to us. Our team is available to help you with any inquiries regarding our services and support.',
            yourName: 'Your Name',
            yourSubject: 'Your Subject',
            yourEmail: 'Your Email',
            yourPhone: 'Your Phone',
            yourMessage: 'Your Message',
            submitMessage: 'Submit Message',
        },
        adminDashboardPage: {
            dashboardTitle: "Admin Dashboard",
            productManagement: "Product Management",
            categoryManagement: "Category Management",
            orderManagement: "Order Management",
            addProductTitle: "Add New Product",
            addProductButton: "Add Product",
            productListTitle: "Product List",
            categoryListTitle: "Category List",
            addCategoryButton: "+ Add New Category",
            footerText: "My Store. All rights reserved.",
            productNameLabel: "Product Name:",
            productNamePlaceholder: "Product Name",
            productPriceLabel: "Price:",
            productPricePlaceholder: "Price",
            productStockChartTitle: "Product Stock Levels",
            categoryDistributionChartTitle: "Product Distribution by Category",
            salesOverviewChartTitle: "Sales Overview (Last 6 Months)",
            userCountTitle: "Total Users",
            topSellingProductsTitle: "Top Selling Products",
            ordersByStatusTitle: "Orders by Status",
            totalRevenue: "Total Revenue",
            totalOrders: "Total Orders",
            totalProducts: "Total Products",
            totalUsers: "Total Users",
            revenueLabel: "Revenue",
            orderCountLabel: "Order Count",
            itemsSoldLabel: "items sold",
            items: "items",
            orderIdHeader: "Order ID",
            userHeader: "User",
            dateHeader: "Date",
            totalHeader: "Total",
            paidHeader: "Paid",
            deliveredHeader: "Delivered",
            recentOrdersTitle: "Recent Orders",
            userRegistrationTitle: "User Registration Over Time",
            usersRegisteredLabel: "Users Registered",
            errorFetchingStock: "Failed to fetch stock data.",
            errorFetchingCategories: "Failed to fetch category data.",
            errorFetchingSales: "Failed to fetch sales data.",
            errorFetchingUsers: "Failed to fetch user data.",
            errorFetchingTopProducts: "Failed to fetch top products data.",
            errorFetchingOrderStatus: "Failed to fetch order status data.",
            errorFetchingData: "Error fetching data.",
            noStockData: "No stock data available.",
            noCategoryData: "No category data available.",
            noSalesData: "No sales data available.",
            noUserData: "No user data available.",
            noTopProductsData: "No top selling products data available.",
            noOrderStatusData: "No order status data available.",
            noDataAvailable: "No data available to display dashboard.",
            noUserRegistrationData: "No user registration data available.",
            noRecentOrdersData: "No recent orders available.",
            advertisementManagement: "Advertisement Management",
            quantitySoldLabel: "Quantity Sold",
            discountManagement: "Discount Management",

        },
        adminCategoryPage: {
            loadingCategories: "Loading categories...",
            errorFetchingCategories: "Error fetching categories.",
            categoryListTitle: "Category List",
            noCategoriesFound: "No categories to display currently.",
            confirmDelete: (categoryName) => `Are you sure you want to delete the category: "${categoryName}"?`,
            deleteSuccess: "Category deleted successfully!",
            errorDeletingCategory: "An error occurred while deleting the category.",
            editCategory: "Edit Category",
            deleteCategory: "Delete Category",
            editCategoryModalTitle: "Edit Category",
            categoryNameLabel: "Category Name",
            categoryNameRequired: "Category name is required.",
            categoryDescriptionLabel: "Description (Optional)",
            cancelButton: "Cancel",
            saveChangesButton: "Save Changes",
            savingChangesButton: "Saving...",
            updateSuccess: "Category updated successfully!",
            errorUpdatingCategory: "An error occurred while updating the category.",
            addCategoryModalTitle: "Add New Category",
            categoryNameRequiredError: "Category name is required.",
            addSuccess: "Category added successfully!",
            errorAddingCategory: "An error occurred while adding the category.",
            addingButton: "Adding...",
            addButton: "Add Category",
            closeButtonLabel: "Close",
            nameTable: "Name",
            descriptionTable: "Description",
            actionsTable: "Actions",
            noDescription: "No Description",
        },
        adminProduct: {
            confirmDelete:"Are you sure you want to delete the product?",
            deleteSuccess: "Product deleted successfully!",
            errorDeletingProduct: "An error occurred while deleting the product.",
        },
        productAdmin: {
            addProductTitle: "Add New Product",
            editProductTitle: "Edit Product",
            productNameLabel: "Product Name",
            productNameEn: "Product Name (English)",
            productNameAr: "Product Name (Arabic)",
            descriptionLabel: "Description",
            descriptionEn: "Description (English)",
            descriptionAr: "Description (Arabic)",
            priceLabel: "Price",
            categoryLabel: "Category",
            categoryEn: "Category (English)",
            categoryAr: "Category (Arabic)",
            brandLabel: "Brand",
            brandEn: "Brand (English)",
            brandAr: "Brand (Arabic)",
            imageLabel: "Product Image",
            imageOptional: "Product Image (Optional to change current)",
            imageRequired: "Product Image is required.",
            submitButton: "Add Product",
            submittingButton: "Adding...",
            updateButton: "Save Changes",
            updatingButton: "Saving...",
            cancelButton: "Cancel",
            nameAndPriceRequired: "Product name and price are required.",
            addSuccess: "Product added successfully!",
            addError: "An error occurred while adding the product.",
            updateSuccess: "Product updated successfully!",
            updateError: "An error occurred while updating the product.",
            productListTitle: "Product List",
            errorFetchingProducts: "Error fetching products.",
            noProducts: "No products to display currently.",
            confirmDelete: (productName) => `Are you sure you want to delete the product: "${productName}"?`,
            deleteSuccess: "Product deleted successfully!",
            errorDeletingProduct: "An error occurred while deleting the product.",
            imageTable: "Image",
            nameTable: "Name",
            descriptionTable: "Description",
            categoryTable: "Category",
            priceTable: "Price",
            actionsTable: "Actions",
            noDescription: "No Description",
            uncategorized: "Uncategorized",
            addProductButton: "Add Product",
            addButton: "Add Product",
        },
      advertisementAdmin: {
                advertisementListTitle: "Advertisement List",
                addAdvertisementButton: "Add Advertisement",
                noAdvertisements: "No advertisements to display currently.",
                titleEn: "Title (English)",
                titleAr: "Title (Arabic)",
                descriptionEn: "Description (English)",
                descriptionAr: "Description (Arabic)",
                linkLabel: "Link",
                typeLabel: "Type",
                typeSlide: "Slide",
                typeSideOffer: "Side Offer",
                typeWeeklyOffer: "Weekly Offer",
                orderLabel: "Order",
                imageLabel: "Image",
                isActive: "Active",
                addButton: "Add Advertisement",
                imageTable: "Image",
                titleTable: "Title",
                descriptionTable: "Description",
                linkTable: "Link",
                typeTable: "Type",
                activeTable: "Active",
                orderTable: "Order",
                actionsTable: "Actions",
                editAdvertisementTitle: "Edit Advertisement",
                updateButton: "Save Changes",
                updateSuccess: "Advertisement updated successfully!",
                confirmDelete: "Are you sure you want to delete the advertisement?",
                deleteSuccess: "Advertisement deleted successfully!",
            },
            discountAdmin: {
                discountListTitle: "Discount List",
                addDiscountButton: "Add Discount",
                noDiscounts: "No discounts to display currently.",
                codeLabel: "Code",
                discountPercentageLabel: "Discount Percentage",
                startDateLabel: "Start Date",
                endDateLabel: "End Date",
                addButton: "Add Discount",
                codeTable: "Code",
                discountPercentageTable: "Discount Percentage",
                startDateTable: "Start Date",
                endDateTable: "End Date",
                actionsTable: "Actions",
                editDiscountTitle: "Edit Discount",
                updateButton: "Save Changes",
                updateSuccess: "Discount updated successfully!",
                confirmDelete: "Are you sure you want to delete the discount?",
                deleteSuccess: "Discount deleted successfully!",
                percentageLabel: "Percentage",
                fixedAmountLabel: "Fixed Amount",
                minOrderAmountLabel: "Min Order Amount",
                maxDiscountAmountLabel: "Max Discount Amount",
                isActive: "Active",
                amountExclusive: "Cannot provide both percentage and fixed amount.",
                typeTable: "Type",
                valueTable: "Value",
                minOrderTable: "Min Order",
                maxDiscountTable: "Max Discount",
                activeTable: "Active",
                percentageType: "Percentage",
                fixedAmountType: "Fixed Amount",
                submittingButton: "Submitting...",
                updatingButton: "Updating...",
            },
        features: {
            freeShipping: "Free Shipping",
            freeShippingDesc: "Free shipping on all orders over $100",
            support247: "Support 24/7",
            support247Desc: "Get help anytime you need it",
            onlinePayment: "Online Payment",
            onlinePaymentDesc: "Secure online payment options",
            easyReturn: "Easy Return",
            easyReturnDesc: "Hassle-free returns within 30 days",
        },
        aboutUsPage: {
            title: 'TechXpress - Your Go-To Electronics Store',
            commitment: 'At TechXpress, we are committed to bringing you the latest and greatest in electronics. Whether you’re looking for cutting-edge smartphones, high-performance laptops, or premium accessories, we offer a wide selection of top-quality products at unbeatable prices.',
            belief: 'We believe in providing an exceptional shopping experience by ensuring fast delivery, secure payment options, and outstanding customer service. Our goal is to make tech shopping simple, reliable, and enjoyable for everyone.',
            explore: 'Explore our collection and stay ahead with the latest technology trends. Your satisfaction is our priority!',
            imageAlt: "Handshake representing partnership and trust"
        },
        trendingProducts: "Trending Products",
        trendingDesc: "Check out our most popular products this week.",
        wishlistPage: {
            wishlistTitle: "My Wishlist",
            loadingWishlist: "Loading wishlist...",
            pleaseLogin: "Please log in to view your wishlist.",
            emptyWishlist: "Your wishlist is currently empty.",
        },
        auth: {

            emailLabel: "Email",
            loginTitle: "Login",
            passwordLabel: "Password",
            forgotPassword: "Forgot Password?",
            loginButton: "Login",
            registerPrompt: "Don't have an account?",
            registerLink: "Sign up here",
            registerTitle: "Sign Up",
            nameLabel: "Name",
            registerButton: "Sign Up",
            loginFailed: "Login failed. Please check your credentials.",
            noAccount: "Don't have an account?",
            loggingInButton: "Logging in...",
            signUpLink: "Sign up here",
            loginSuccess: "Login successful!",
            confirmPasswordLabel: "Confirm Password",
            loginPrompt: "Already have an account?",
            loginLink: "Login here",
            passwordMismatch: "Passwords do not match",
            registering: "Registering...",
            registrationSuccess: "Registration successful!",
            haveAccount: "Already have an account?",
            alreadyHaveAccount : "Already have an account?",
            signInLink: "Sign In Here",
            submittingButton: "Submit",
            forgotPasswordTitle: "Forgot Password",
            forgotPasswordInstructions: "Enter your email address to reset your password.",
            sendResetLink: "Send Reset Link",
            loginNow: "Login Now",

        }
    },
 
    ar: {
        loginPage: {
            title: "تسجيل الدخول",
            emailLabel: "البريد الالكتروني",
            passwordLabel: "كلمة المرور",
            loginButton: "تسجيل الدخول",
            loginFailed: "فشل تسجيل الدخول. يرجى التحقق من بياناتك.",
            noAccount: "ليس لديك حساب؟",
            loggingInButton: "جار تسجيل الدخول",
            signUpLink: " قم بالتسجيل هنا",
            loginSuccess: "تم تسجيل الدخول بنجاح!",
          
        },

        registerPage: {
            title: "التسجيل",
            nameLabel: "الاسم",
            emailLabel: "البريد الالكتروني",
            passwordLabel: "كلمة المرور",
            confirmPasswordLabel: "تاكيد كلمة المرور",
            registerButton: "تسجيل",
            passwordMismatch: "كلمة المرور غير متطابقة",
            registering: "جار التسجيل...",
            registrationSuccess: "تم التسجيل بنجاح!",
            haveAccount: "لديك حساب بالفعل؟",
            loginTitle: "تسجيل الدخول",
            registerTitle: "التسجيل",
            alreadyHaveAccount : "لديك حساب بالفعل؟",
            signInLink: "قم بتسجيل الدخول هنا",
            submitButton: "اضافة",
        },
        general: {
            loading: "جاري التحميل...",
            error: "خطأ",
            view: "عرض المنتج",
            shopNow: "تسوق الآن",
            errorFetchingProducts: "فشل تحميل المنتجات.",
            errorFetchingOrders: "فشل جلب الطلبات.",
            errorFetchingUsers: "فشل جلب المستخدمين.",
            errorFetchingCategories: "فشل جلب الفئات.",
            unnamedProduct: "منتج غير مسمى",
            total: "الإجمالي",
            errorFetchingData: "فشل جلب البيانات.",
        },
       
        homepage: {
            discountsTitle: "الخصومات",
            discountCode: "رمز الخصم",
            off: "خصم",
            validUntil: "صلاحية حتى",
            copyCode: "نسخ الرمز",
            discountCode: "رمز الخصم",
            copied: "تم نسخ الرمز بنجاح!",
        },
        shopPage: {
            searchProduct: "البحث عن منتج",
            searchHere: "ابحث هنا...",
            priceRange: "نطاق السعر",
            filterByBrand: "التصفية حسب الماركة",
            sortBy: "الترتيب حسب:",
            popularity: "الشعبية",
            priceLowToHigh: "السعر: من الأقل للأعلى",
            priceHighToLow: "السعر: من الأعلى للأقل",
            nameAZ: "الاسم (أ-ي)",
            showingItems: "عرض",
            items: "عنصر",
            noProductsFound: "لم يتم العثور على منتجات مطابقة لمعايير البحث.",
            addToCart: "أضف إلى السلة",
            removeFromCart: "إزالة من السلة",
            addToFavorites: "أضف إلى المفضلة",
            removeFromFavorites: "إزالة من المفضلة",
            currencySymbol: "ج.م",
            locale: 'ar-EG',
            filter: "تصفية",
            showFilters: "عرض الفلاتر",
        },
        productDetailsPage: {
            quantity: "الكمية",
            securePayment: "دفع آمن",
            fastShipping: "شحن سريع",
            qualityGuarantee: "ضمان الجودة",
            productDescription: "وصف المنتج",
            pleaseLoginToAddFavorites: "يرجى تسجيل الدخول لإضافة المنتج إلى المفضلة.",
            pleaseLoginToAddCart: "يرجى تسجيل الدخول لإضافة المنتج إلى السلة.",
        },
        cartPage: {
            shoppingCart: "سلة التسوق",
            cartEmpty: "سلتك فارغة.",
            cartEmptyDesc: "يبدو أنك لم تقم بإضافة أي شيء إلى سلة التسوق بعد.",
            continueShopping: "متابعة التسوق",
            removeItem: "إزالة العنصر",
            cartTotal: "إجمالي السلة",
            proceedToCheckout: "المتابعة إلى الدفع",
            loadingCart: "جاري تحميل السلة...",
            cartEmptyCheckout: "سلتك فارغة. أضف عناصر قبل المتابعة للدفع.",
            cartEmptyCheckoutRedirect: "سلتك فارغة. جاري إعادة التوجيه لصفحة التسوق...",
            decreaseQuantity: "تقليل الكمية",
            increaseQuantity: "زيادة الكمية",
            productQuantity: "كمية المنتج",
        },
        checkoutPage: {
            checkout: "الدفع",
            orderSummary: "ملخص الطلب",
            shippingAndPayment: "الشحن والدفع",
            shippingAddress: "عنوان الشحن",
            paymentMethod: "طريقة الدفع",
            placeOrder: "تأكيد الطلب",
            placingOrder: "جاري تأكيد الطلب...",
            orderPlacedSuccessTitle: "تم تأكيد الطلب بنجاح!",
            orderPlacedSuccessMessage: "شكراً لك على عملية الشراء. سيتم إعادة توجيهك إلى الصفحة الرئيسية قريباً.",
            redirecting: "جاري إعادة التوجيه...",
            orderPlacementFailed: "فشل تأكيد الطلب.",
            orderPlacementError: "خطأ في تأكيد الطلب",
            pleaseLoginToCheckout: "يرجى تسجيل الدخول للمتابعة إلى الدفع.",
            shippingPaymentRequired: "يرجى توفير عنوان الشحن وعنوان الدفع.",
            checkoutPlaceholder: "جاري المتابعة إلى الدفع...",
            placeOrderPlaceholder: "جاري تأكيد الطلب... (تحتاج منطق الخلفية)",
            enterAddressPlaceholder: "أدخل العنوان",
            enterCityPlaceholder: "أدخل المدينة",
            enterPostalCodePlaceholder: "أدخل الرمز البريدي",
            enterCountryPlaceholder: "أدخل البلد",
            cashOnDelivery: "الدفع عند الاستلام",
            checkoutTitle: "إتمام الطلب",
            selectPaymentMethod: "اختر طريقة الدفع",
            selectShippingAddress: "اختر عنوان الشحن",
        },
        adminOrdersPage: {
            allOrders: "جميع الطلبات",
            orderID: "رقم الطلب",
            user: "المستخدم",
            date: "التاريخ",
            paid: "مدفوع",
            delivered: "تم التوصيل",
            details: "التفاصيل",
            loadingOrders: "جاري تحميل الطلبات...",
            errorFetchingOrders: "فشل في جلب الطلبات.",
            noOrdersFound: "لم يتم العثور على طلبات.",
            yes: "نعم",
            no: "لا",
            orderDetails: "تفاصيل الطلب",
            shippingAddress: "عنوان الشحن",
            address: "العنوان",
            status: "الحالة",
            notDelivered: "لم يتم التوصيل",
            markAsDelivered: "تحديث الحالة للتوصيل",
            customerInfo: "معلومات العميل",
            name: "الاسم",
            email: "البريد الالكتروني",
            paymentMethod: "طريقة الدفع",
            method: "طريقة",
            notPaid: "لم يتم الدفع",
            markAsPaid: "تحديث الحالة للدفع",
            orderSummary: "ملخص الطلب",
            itemsPrice: "سعر المنتجات",
            shippingPrice: "سعر الشحن",
            taxPrice: "سعر الضريبة",
            totalPrice: "السعر الكلي",
            orderItems: "عناصر الطلب",
            dates: "التاريخ",
            orderedAt: "تم الطلب في",
            orderDate: "تاريخ الطلب",
            deliveryDate: "تاريخ التوصيل",
        },
        heroSection: {
            bigSale: "تخفيضات كبرى",
            comboOffer: "عرض الباقة",
            installment: "متوفر بالتقسيط",
            weeklySale: "عروض الأسبوع",
            weeklyDesc: "لا تفوت عروضنا الأسبوعية المذهلة! خصم يصل إلى",
            off: "خصم",
            thisWeek: "هذا الأسبوع.",
            languageArabic: "العربية",
            languageEnglish: "English",
            lightMode: "وضع الإضاءة",
            darkMode: "الوضع الداكن",
        },
        heroSlidesData: [
            {
                
                image: require("../Assets/hero5.png"), 
                title: "حزمة الأمان القصوى",
                desc: "كاميرات مراقبة متطورة مع إمكانية الوصول عن بعد.",
                price: "28,320.00 ج.م",
            },
            {
                image: require("../Assets/hero2.png"),
                title: "باقة المنزل الذكي",
                desc: "تحكم في منزلك من هاتفك.",
                price: "14,200.00 ج.م",
            },
            {
                image:require("../Assets/hero4.png"),
                title: "مجموعة كاميرات المكتب",
                desc: "أمن عملك بكشف ذكاء اصطناعي ذكي.",
                price: "17,990.00 ج.م",
            },
            {
                image: require("../Assets/hero6.png"),
                title: "كاميرا خارجية احترافية",
                desc: "مقاومة للعوامل الجوية، رؤية ليلية، والمزيد.",
                price: "9,500.00 ج.م",
            },
        ],
        heroSideOffers: {
            iphoneOffer: {
                productName: "آيفون 12 برو ماكس",
                price: "12,480.00 ج.م",
                image: require("../Assets/hero4.png"),
            },
        },
        categories: {
            "All Categories": "جميع الفئات",
            Watch: "ساعات",
            Speaker: "سماعات",
            Camera: "كاميرات",
            Phone: "هواتف",
            Headphone: "سماعات رأس",
            Laptop: "لابتوب",
            TV: "تلفزيونات",
        },
        brands: {
            "All Brands": "جميع الماركات",
        },
        topBar: {
            currency: "العملة",
            language: "اللغة",
            home: "الرئيسية",
            shop: "المتجر",
            aboutUs: "من نحن",
            contactUs: "اتصل بنا",
            dashboard: "لوحة التحكم",
            logout: "تسجيل الخروج",
            helloGuest: "أهلاً بك يا زائر",
            signIn: "تسجيل الدخول",
            register: "التسجيل",
            light: "فاتح",
            dark: "داكن",
            helloUser: "مرحباً",
            languageArabic: "العربية",
            languageEnglish: "English",
            lightMode: "وضع الإضاءة",
            darkMode: "الوضع الداكن",
        },
        mainHeader: {
            siteName: "تيكسبرس",
            searchPlaceholder: "ابحث عن المنتجات...",
            allCategories: "الكل",
            hotline: "الخط الساخن",
            myWishlist: "قائمة المفضلة",
            myCart: "سلتي",
            searchError: "حدث خطأ أثناء البحث.",
        },
        contactUsPage: {
            title: 'اتصل بنا',
            description: 'هل لديك أي أسئلة أو تحتاج إلى مساعدة؟ لا تتردد في التواصل معنا. فريقنا متاح لمساعدتك في أي استفسارات بخصوص خدماتنا ودعمنا.',
            yourName: 'اسمك',
            yourSubject: 'موضوع الرسالة',
            yourEmail: 'بريدك الإلكتروني',
            yourPhone: 'رقم هاتفك',
            yourMessage: 'رسالتك',
            submitMessage: 'إرسال الرسالة',
        },
        adminDashboardPage: {
            dashboardTitle: "لوحة تحكم المتجر",
            productManagement: "إدارة المنتجات",
            categoryManagement: "إدارة الفئات",
            orderManagement: "إدارة الطلبات",
            addProductTitle: "إضافة منتج جديد",
            addProductButton: "إضافة منتج",
            productListTitle: "قائمة المنتجات",
            categoryListTitle: "قسم الفئات",
            addCategoryButton: "+ إضافة فئة جديدة",
            footerText: "متجري. جميع الحقوق محفوظة.",
            productNameLabel: "اسم المنتج:",
            productNamePlaceholder: "اسم المنتج",
            productPriceLabel: "السعر:",
            productPricePlaceholder: "السعر",
            productStockChartTitle: "مستويات مخزون المنتجات",
            categoryDistributionChartTitle: "توزيع المنتجات حسب الفئة",
            salesOverviewChartTitle: "نظرة عامة على المبيعات (آخر 6 أشهر)",
            userCountTitle: "إجمالي المستخدمين",
            topSellingProductsTitle: "المنتجات الأكثر مبيعًا",
            ordersByStatusTitle: "الطلبات حسب الحالة",
            totalRevenue: "إجمالي الإيرادات",
            totalOrders: "إجمالي الطلبات",
            totalProducts: "إجمالي المنتجات",
            totalUsers: "إجمالي المستخدمين",
            revenueLabel: "الإيرادات",
            orderCountLabel: "عدد الطلبات",
            itemsSoldLabel: "عنصر تم بيعه",
            items: "عناصر",
            orderIdHeader: "رقم الطلب",
            userHeader: "المستخدم",
            dateHeader: "التاريخ",
            totalHeader: "الإجمالي",
            paidHeader: "مدفوع",
            deliveredHeader: "تم التوصيل",
            recentOrdersTitle: "الطلبات الأخيرة",
            userRegistrationTitle: "تسجيل المستخدمين بمرور الوقت",
            usersRegisteredLabel: "المستخدمون المسجلون",
            errorFetchingStock: "فشل جلب بيانات المخزون.",
            errorFetchingCategories: "فشل جلب بيانات الفئات.",
            errorFetchingSales: "فشل جلب بيانات المبيعات.",
            errorFetchingUsers: "فشل جلب بيانات المستخدمين.",
            errorFetchingTopProducts: "فشل جلب بيانات المنتجات الأكثر مبيعًا.",
            errorFetchingOrderStatus: "فشل جلب بيانات حالة الطلبات.",
            errorFetchingData: "خطأ في جلب البيانات.",
            noStockData: "لا توجد بيانات مخزون متاحة.",
            noCategoryData: "لا توجد بيانات فئات متاحة.",
            noSalesData: "لا توجد بيانات مبيعات متاحة.",
            noUserData: "لا توجد بيانات مستخدمين متاحة.",
            noTopProductsData: "لا توجد بيانات منتجات أكثر مبيعًا متاحة.",
            noOrderStatusData: "لا توجد بيانات حالة طلبات متاحة.",
            noDataAvailable: "لا توجد بيانات متاحة لعرض لوحة التحكم.",
            noUserRegistrationData: "لا توجد بيانات تسجيل مستخدمين متاحة.",
            noRecentOrdersData: "لا توجد طلبات أخيرة متاحة.",

            advertisementManagement: "ادارة الاعلانات",
            quantitySoldLabel: "الكمية المباعة",
            discountManagement: "ادارة الخصومات",
        },
        adminCategoryPage: {
            loadingCategories: "جاري تحميل الفئات...",
            errorFetchingCategories: "حدث خطأ أثناء جلب الفئات.",
            categoryListTitle: "قائمة الفئات",
            noCategoriesFound: "لا توجد فئات لعرضها حاليًا.",
            confirmDelete: (categoryName) => `هل أنت متأكد أنك تريد حذف الفئة: "${categoryName}"؟`,
            deleteSuccess: "تم حذف الفئة بنجاح!",
            errorDeletingCategory: "حدث خطأ أثناء حذف الفئة.",
            editCategory: "تعديل الفئة",
            deleteCategory: "حذف الفئة",
            editCategoryModalTitle: "تعديل الفئة",
            categoryNameLabel: "اسم الفئة",
            categoryNameRequired: "اسم الفئة مطلوب.",
            categoryDescriptionLabel: "الوصف (اختياري)",
            cancelButton: "إلغاء",
            saveChangesButton: "حفظ التغييرات",
            savingChangesButton: "جاري الحفظ...",
            updateSuccess: "تم تحديث الفئة بنجاح!",
            errorUpdatingCategory: "حدث خطأ أثناء تحديث الفئة.",
            addCategoryModalTitle: "إضافة فئة جديدة",
            categoryNameRequiredError: "اسم الفئة مطلوب.",
            addSuccess: "تمت إضافة الفئة بنجاح!",
            errorAddingCategory: "حدث خطأ أثناء إضافة الفئة.",
            addingButton: "جاري الإضافة...",
            addButton: "إضافة الفئة",
            closeButtonLabel: "إغلاق",
            nameTable: "الاسم",
            descriptionTable: "الوصف",
            actionsTable: "الإجراءات",
            noDescription: "لا يوجد وصف",
            addProductButton: "ائضافة منتج",
            addButton: "ائضافة",
        },
         adminProduct: {
            confirmDelete : "هل تريد حذف المنتج ؟",
            deleteSuccess: "تم حذف المنتج بنجاح!",
            errorDeletingProduct: "حدث خطاء اثناء حذف المنتج.",
        },

        productAdmin: {
            addProductTitle: "إضافة منتج جديد",
            editProductTitle: "تعديل المنتج",
            productNameLabel: "اسم المنتج",
            productNameEn: "اسم المنتج (الإنجليزية)",
            productNameAr: "اسم المنتج (العربية)",
            descriptionLabel: "الوصف",
            descriptionEn: "الوصف (الإنجليزية)",
            descriptionAr: "الوصف (العربية)",
            priceLabel: "السعر",
            categoryLabel: "الفئة",
            categoryEn: "الفئة (الإنجليزية)",
            categoryAr: "الفئة (العربية)",
            brandLabel: "الماركة",
            brandEn: "الماركة (الإنجليزية)",
            brandAr: "الماركة (العربية)",
            imageLabel: "صورة المنتج",
            imageOptional: "صورة المنتج (اختياري للتغيير)",
            imageRequired: "صورة المنتج مطلوبة.",
            submitButton: "إضافة المنتج",
            submittingButton: "جاري الإضافة...",
            updateButton: "حفظ التغييرات",
            updatingButton: "جاري الحفظ...",
            cancelButton: "إلغاء",
            nameAndPriceRequired: "اسم المنتج والسعر مطلوبان.",
            addSuccess: "تم إضافة المنتج بنجاح!",
            addError: "حدث خطأ أثناء إضافة المنتج.",
            updateSuccess: "تم تحديث المنتج بنجاح!",
            updateError: "حدث خطأ أثناء تحديث المنتج.",
            productListTitle: "قائمة المنتجات",
            errorFetchingProducts: "حدث خطأ أثناء جلب المنتجات.",
            noProducts: "لا توجد منتجات لعرضها حاليًا.",
            confirmDelete: (productName) => `هل أنت متأكد أنك تريد حذف المنتج: "${productName}"؟`,
            deleteSuccess: "تم حذف المنتج بنجاح!",
            errorDeletingProduct: "حدث خطأ أثناء حذف المنتج.",
            imageTable: "الصورة",
            nameTable: "الاسم",
            descriptionTable: "الوصف",
            categoryTable: "الفئة",
            priceTable: "السعر",
            actionsTable: "الإجراءات",
            noDescription: "لا يوجد وصف",
            uncategorized: "غير مصنف",
        },
   advertisementAdmin: {
                advertisementListTitle: "قائمة الاعلانات",
                addAdvertisementButton: "اضافة اعلان",
                noAdvertisements: "لا يوجد اعلانات حاليا",
                titleEn: "العنوان (الانجليزية)",
                titleAr: "العنوان (العربية)",
                descriptionEn: "الوصف (الانجليزية)",
                descriptionAr: "الوصف (العربية)",
                linkLabel: "الرابط",
                typeLabel: "النوع",
                typeSlide: "Slide",
                typeSideOffer: "Side Offer",
                typeWeeklyOffer: "Weekly Offer",
                orderLabel: "الترتيب",
                imageLabel: "الصورة",
                isActive: "الحالة",
                addButton: "اضافة اعلان",
                imageTable: "الصورة",
                titleTable: "العنوان",
                descriptionTable: "الوصف",
                linkTable: "الرابط",
                typeTable: "النوع",
                activeTable: "الحالة",
                orderTable: "الترتيب",
                actionsTable: "الإجراءات",
                editAdvertisementTitle: "تعديل الاعلان",
                updateButton: "حفظ التغييرات",
                updateSuccess: "تم تحديث الاعلان بنجاح!",
                confirmDelete: "هل انت متاكد من حذف الاعلان؟",
                deleteSuccess: "تم حذف الاعلان بنجاح!",
            },
            discountAdmin: {
                discountListTitle: "قائمة الخصومات",
                addDiscountButton: "اضافة خصم",
                noDiscounts: "لا يوجد خصومات حاليا",
                codeLabel: "الكود",
                discountPercentageLabel: "نسبة الخصم",
                startDateLabel: "تاريخ البدء",
                endDateLabel: "تاريخ الانتهاء",
                addButton: "اضافة خصم",
                codeTable: "الكود",
                discountPercentageTable: "نسبة الخصم",
                startDateTable: "تاريخ البدء",
                endDateTable: "تاريخ الانتهاء",
                actionsTable: "الإجراءات",
                editDiscountTitle: "تعديل الخصم",
                updateButton: "حفظ التغييرات",
                updateSuccess: "تم تحديث الخصم بنجاح!",
                confirmDelete: "هل انت متاكد من حذف الخصم؟",
                deleteSuccess: "تم حذف الخصم بنجاح!",
                percentageLabel: "نسبة",
                fixedAmountLabel: "مبلغ ثابت",
                minOrderAmountLabel: "الحد الادنى للطلب",
                maxDiscountAmountLabel: "الحد الاقصى للخصم", // تم التصحيح
                isActive: "الحالة",
                amountExclusive: "لا يمكن توفير نسبة ومبلغ ثابت متزامنين.",
                typeTable: "النوع",
                valueTable: "القيمة",
                minOrderTable: "الحد الادنى للطلب",
                maxDiscountTable: "الحد الاقصى للخصم", // تم التصحيح
                activeTable: "الحالة",
                percentageType: "نسبة",
                fixedAmountType: "مبلغ ثابت",
                submittingButton: "جاري الإضافة...", // تم التصحيح
                updatingButton: "جاري التحديث...", // تم التصحيح
            },
     
        features: {
            freeShipping: "شحن مجاني",
            freeShippingDesc: "شحن مجاني على جميع الطلبات فوق 100 دولار",
            support247: "دعم 24/7",
            support247Desc: "احصل على المساعدة في أي وقت تحتاجه",
            onlinePayment: "الدفع عبر الإنترنت",
            onlinePaymentDesc: "خيارات دفع آمنة عبر الإنترنت",
            easyReturn: "إرجاع سهل",
            easyReturnDesc: "إرجاع بدون متاعب خلال 30 يومًا",
        },
        aboutUsPage: {
            title: 'تيكسبرس - متجرك المفضل للإلكترونيات',
            commitment: 'في تيكسبرس، نحن ملتزمون بتقديم أحدث وأفضل المنتجات الإلكترونية. سواء كنت تبحث عن هواتف ذكية متطورة، أجهزة لابتوب عالية الأداء، أو إكسسوارات مميزة، نقدم مجموعة واسعة من المنتجات عالية الجودة بأسعار لا تُضاهى.',
            belief: 'نؤمن بتقديم تجربة تسوق استثنائية من خلال ضمان التوصيل السريع، خيارات الدفع الآمنة، وخدمة العملاء المتميزة. هدفنا هو جعل تسوق التكنولوجيا بسيطاً، موثوقاً، وممتعاً للجميع.',
            explore: 'استكشف مجموعتنا وابقَ على اطلاع بأحدث اتجاهات التكنولوجيا. رضاكم هو أولويتنا!',
            imageAlt: "مصافحة تمثل الشراكة والثقة"
        },
        trendingProducts: "المنتجات الأكثر رواجًا",
        trendingDesc: "اكتشف منتجاتنا الأكثر شعبية هذا الأسبوع.",
        wishlistPage: {
            wishlistTitle: "قائمة المفضلة",
            loadingWishlist: "جاري تحميل قائمة المفضلة...",
            pleaseLogin: "يرجى تسجيل الدخول لعرض قائمة المفضلة الخاصة بك.",
            emptyWishlist: "قائمة المفضلة فارغة حالياً.",
        },
        //  auth: {

        //     emailLabel: "Email",
        //     loginTitle: "Login",
        //     passwordLabel: "Password",
        //     forgotPassword: "Forgot Password?",
        //     loginButton: "Login",
        //     registerPrompt: "Don't have an account?",
        //     registerLink: "Sign up here",
        //     registerTitle: "Sign Up",
        //     nameLabel: "Name",
        //     registerButton: "Sign Up",
        //     loginFailed: "Login failed. Please check your credentials.",
        //     noAccount: "Don't have an account?",
        //     loggingInButton: "Logging in...",
        //     signUpLink: "Sign up here",
        //     loginSuccess: "Login successful!",
        //     confirmPasswordLabel: "Confirm Password",
        //     loginPrompt: "Already have an account?",
        //     loginLink: "Login here",
        //     passwordMismatch: "Passwords do not match",
        //     registering: "Registering...",
        //     registrationSuccess: "Registration successful!",
        //     haveAccount: "Already have an account?",
        //     alreadyHaveAccount : "Already have an account?",
        //     signInLink: "Sign In Here",
        //     submittingButton: "Submit",
        //     forgotPasswordTitle: "Forgot Password",
        //     forgotPasswordInstructions: "Enter your email address to reset your password.",
        //     sendResetLink: "Send Reset Link",
        //     loginNow: "Login Now",

        // }
        auth: {
            emailLabel: "البريد الالكتروني",
            loginTitle: "تسجيل الدخول",
            passwordLabel: "كلمة المرور",
            forgotPassword: "هل نسيت كلمة المرور؟",
            loginButton: "تسجيل الدخول",
            registerPrompt: "ليس لديك حساب؟",
            registerLink: "انشاء حساب جديد",
            registerTitle: "انشاء حساب",
            nameLabel: "الاسم",
            registerButton: "انشاء حساب",
            loginFailed: "فشل تسجيل الدخول. يرجى التحقق من اعتماداتك.",
            noAccount: "ليس لديك حساب؟",
            loggingInButton: "جار التسجيل...",
            signUpLink: "انشاء حساب جديد",
            loginSuccess: "تم تسجيل الدخول بنجاح!",
            confirmPasswordLabel: "تأكيد كلمة المرور",
            loginPrompt: "لديك حساب؟",
            loginLink: "تسجيل الدخول هنا",
            passwordMismatch: "كلمات المرور غير متطابقة",
            registering: "جار التسجيل...",
            registrationSuccess: "تم التسجيل بنجاح!",
            haveAccount: "لديك حساب؟",
            alreadyHaveAccount : "لديك حساب؟",
            signInLink: "تسجيل الدخول هنا",
            submittingButton: "تأكيد",
            forgotPasswordTitle: "نسيت كلمة المرور",
            forgotPasswordInstructions: "ادخل عنوان البريد الالكتروني لاستعادة كلمة المرور الخاصة بك.",
            sendResetLink: "ارسال رابط استعادة",
            loginNow: "تسجيل الدخول الان",
            
        }
    },
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const savedLanguage = localStorage.getItem('appLanguage');
        return savedLanguage || 'en';
    });
    useEffect(() => {
        localStorage.setItem('appLanguage', language);
    }, [language]);
    const toggleLanguage = () => {
        setLanguage(prevLanguage => (prevLanguage === 'en' ? 'ar' : 'en'));
    };
    const changeLanguage = (newLanguage) => {
        if (translations[newLanguage]) {
            setLanguage(newLanguage);
        } else {
            console.warn(`Language "${newLanguage}" is not supported.`);
        }
    };

const t = (key) => {
        const keys = key.split('.'); 
        let currentTranslation = translations[language]; 
        for (let i = 0; i < keys.length; i++) {
            if (currentTranslation && typeof currentTranslation === 'object' && keys[i] in currentTranslation) {
                currentTranslation = currentTranslation[keys[i]];
            } else {
                console.warn(`Translation missing for key: "${key}" in "${language}" language. Falling back to English.`);
                let englishTranslation = translations['en']; 
                for (let j = 0; j < keys.length; j++) {
                    if (englishTranslation && typeof englishTranslation === 'object' && keys[j] in englishTranslation) {
                        englishTranslation = englishTranslation[keys[j]];
                    } else {
                        console.error(`Translation not found for key: "${key}" in English.`);
                        return key; 
                    }
                }
                return englishTranslation;
            }
        }

       if (typeof currentTranslation === 'function') {
            return (...args) => currentTranslation(...args);
        }

        return currentTranslation; 
    };

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};
export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
