import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
ar:{
  "general": {
    "loading": "جاري التحميل...",
    "error": "خطأ",
    "notApplicable": "لا ينطبق",
    "unnamedItem": "عنصر غير مسمى",
    "priceNotAvailable": "السعر غير متاح",
    "shopNow": "تسوق الآن",
    "currencySymbol": "ر.س",
    "off": "خصم",
    "noImage": "لا توجد صورة",
    "errorFetchingData": "فشل جلب البيانات. يرجى المحاولة لاحقاً.",
    "resetting": "جاري إعادة التعيين...",
    "unnamedProduct": "منتج غير مسمى",
    "imageFailedToLoad": "فشل تحميل الصورة",
    "noImageAvailable": "لا توجد صورة متاحة",
    "currencyCode": "SAR",
    "viewImage": "عرض الصورة",
    "thumbnail": "صورة مصغرة",
    "decreaseQuantity": "تقليل الكمية",
    "increaseQuantity": "زيادة الكمية",
    "productQuantity": "كمية المنتج",
    "subtotal": "المجموع الفرعي",
    "total": "الإجمالي",
    "inCartShort": "في السلة",
    "addToCartShort": "أضف",
    "removeFromWishlist": "إزالة من المفضلة",
    "addToWishlist": "أضف للمفضلة",
    "description": "الوصف",
    "submitting": "جاري الإرسال...",
    "verifyHuman": "الرجاء التحقق أنك لست روبوتاً.",
    "sending": "جاري الإرسال...",
    "apiError": "عنوان API غير معرف.",
    "view":"عرض",
    "pleaseWait": "يرجى الانتظار",
    "image":"صورة",
    "clear":"حذف",
  },
  "heroSection": {
    "bigSale": "عرض لفترة محدودة",
    "price": "السعر",
    "validFrom": "صالح من",
    "validUntil": "صالح حتى",
    "installment": "أقساط ميسرة",
    "weeklySale": "عروض فلاش أسبوعية!",
    "weeklyDesc": "اكتشف توفيرات لا تصدق على منتجاتك المفضلة! احصل على خصم يصل إلى",
    "thisWeek": "لهذا الأسبوع لفترة محدودة.",
    "allOffersTitle": "اكتشف كل العروض!",
    "allOffersDesc": "استكشف جميع العروض الترويجية والخصومات المتاحة في مكان واحد.",
    "noDataAvailable": "لا توجد عروض مثيرة متاحة حالياً."
  },
  "homepage": {
    "discountsTitle": "أكواد خصم حصرية",
    "discountCode": "كودك",
    "copied": "تم النسخ!",
    "shopByCategory": "تسوق حسب الفئة",
    "loadingCategories": "جاري تحميل الفئات...",
    "categoryFetchError": "فشل جلب الفئات. يرجى المحاولة لاحقاً.",
    "noCategoriesFound": "لم يتم العثور على أي فئات.",
    "categoryImageAlt": "صورة الفئة",
    "unnamedCategory": "فئة غير مسماة",
    "trendingProductsTitle": "المنتجات الأكثر رواجًا",
    "trendingProductsDesc": "اكتشف منتجاتنا الأكثر شعبية هذا الأسبوع.",
    "noTrendingProductsFound": "لم يتم العثور على منتجات رائجة.",
    "trendingProductsDesc": "اكتشف منتجاتنا الأكثر شعبية هذا الأسبوع.",
    "off":"خصم",
    "copyCode": "نسخ الكود",
  },
  "advertisementAdmin": {
    "noDescription": "لا يوجد وصف متاح."
  },
  "productCard": {
    "uncategorized": "غير مصنف",
    "viewProduct": "عرض المنتج",
    "addToCart": "أضف للسلة",
    "inCart": "في السلة", 
    "addToFavorites": "أضف للمفضلة",
    "removeFromFavorites": "في المفضلة",
    "viewProductError": "لا يمكن عرض تفاصيل المنتج: بيانات المنتج مفقودة.",
    "addToFavoritesError": "لا يمكن إضافة المنتج للمفضلة: بيانات المنتج غير مكتملة.",
    "addToCartError": "لا يمكن إضافة المنتج للسلة: بيانات المنتج غير مكتملة.",
    "specialOffer": "عرض خاص",
    "viewDetails": "عرض التفاصيل",
    "variationsAvailable": "المتاحات المتغيرة",
    "variationsAvailable": "المتاحات المتغيرة",
  },
  "features": {
    "freeShipping": "شحن مجاني",
    "freeShippingDesc": "شحن مجاني لجميع الطلبات التي تزيد عن 100 ر.س",
    "support247": "دعم 24/7",
    "support247Desc": "احصل على المساعدة في أي وقت تحتاجها",
    "onlinePayment": "الدفع عبر الإنترنت",
    "onlinePaymentDesc": "خيارات دفع آمنة عبر الإنترنت",
    "easyReturn": "سهولة الإرجاع",
    "easyReturnDesc": "إرجاع خالٍ من المتاعب خلال 30 يومًا"
  },
  "mainHeader": {
    "siteName": "تكنو إكسبرس",
    "searchPlaceholder": "ابحث عن المنتجات...",
    "hotline": "الخط الساخن",
    "myWishlist": "قائمة المفضلة",
    "myCart": "سلتي",
    "myProfile": "ملفي الشخصي",
    "myAccount": "حسابي",
    "loginRegister": "تسجيل الدخول / التسجيل",
    "login": "تسجيل الدخول"
  },
  "topBar": {
    "languageArabic": "العربية",
    "languageEnglish": "English",
    "home": "الرئيسية",
    "shop": "المتجر",
    "aboutUs": "من نحن",
    "contactUs": "اتصل بنا",
    "dashboard": "لوحة التحكم",
    "helloUser": "أهلاً",
    "helloGuest": "أهلاً بالزائر",
    "logout": "تسجيل الخروج",
    "signIn": "تسجيل الدخول",
    "register": "التسجيل",
    "lightMode": "الوضع الفاتح",
    "darkMode": "الوضع الداكن"
  },
  "shopPage": {
    "filter": "تصفية",
    "showFilters": "إظهار المرشحات",
    "filterByCategory": "تصفية حسب الفئة",
    "filterBySubCategory": "تصفية حسب الفئة الفرعية",
    "priceRange": "نطاق السعر",
    "filterByBrand": "تصفية حسب العلامة التجارية",
    "sortBy": "فرز حسب:",
    "popularity": "الشعبية",
    "priceLowToHigh": "السعر: من الأقل للأعلى",
    "priceHighToLow": "السعر: من الأعلى للأقل",
    "nameAZ": "الاسم (أ-ي)",
    "showingItems": "عرض",
    "items": "عنصر",
    "noProductsFound": "لم يتم العثور على منتجات مطابقة لمعاييرك.",
    "errorFetchingProducts": "فشل تحميل المنتجات. يرجى التحقق من اتصالك أو المحاولة مرة أخرى.",
    "resetFilters": "إعادة تعيين الفلاتر",
    "allSubcategories": "جميع الفئات الفرعية",
    "addToCart": "اضافة للسلة",
    "currencyCode": "ريال سعودي",
    "resetFilters": "اعادة تعيين الفلاتر",
    "allSubcategories": "جميع الفئات الفرعية",
    "addToFavorites": "اضافة للمفضلة",
    "filterByOption": "تصفية حسب الخيار",
    "allOptions": "جميع الخيارات",
    "removeFromFavorites": "حذف من المفضلة",

  },
  "brands": {
    "All Brands": "جميع العلامات التجارية",
    "Nike": "نايك",
    "Urban Threads": "اوربان ترديز",
     " Urban Threads": " اوربان ترديز",
    "Dash Athletics": "داش اتلانتيكس",
    "TechGen": "تك جين",


  },
  "wishlistPage": {
    "loadingWishlist": "جاري تحميل قائمة المفضلة...",
    "pleaseLogin": "يرجى تسجيل الدخول لعرض قائمة المفضلة.",
    "emptyWishlist": "قائمة المفضلة فارغة حالياً. ابدأ بإضافة عناصرك المفضلة!",
    "wishlistTitle": "قائمة مفضلاتي",
    "loginRequiredTitle": "الوصول ممنوع",
    "emptyWishlistTitle": "قائمة مفضلتك فارغة!",
    "addedToWishlist": "تمت اضافة المنتج لقائمة المفضلة.",
  },
  "auth": {
    "resetPasswordTitle": "إعادة تعيين كلمة المرور",
    "tokenExpired": "الرابط مفقود أو غير صالح.",
    "tokenExpiredOrInvalid": "هذا الرابط غير صالح أو انتهت صلاحيته.",
    "passwordMismatch": "كلمتا المرور غير متطابقتين.",
    "passwordResetSuccess": "تم إعادة تعيين كلمة المرور بنجاح. سيتم توجيهك لصفحة تسجيل الدخول.",
    "passwordResetError": "فشل في إعادة تعيين كلمة المرور.",
    "newPasswordLabel": "كلمة المرور الجديدة",
    "confirmNewPasswordLabel": "تأكيد كلمة المرور الجديدة",
    "requestNewLink": "طلب رابط جديد",
    "resetPasswordButton": "إعادة تعيين كلمة المرور",
    "verifyingLink": "جاري التحقق من الرابط...",
    "passwordMinLength": "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.",
    "registerTitle": "إنشاء حسابك",
    "nameLabel": "الاسم بالكامل",
    "emailLabel": "عنوان البريد الإلكتروني",
    "passwordLabel": "كلمة المرور",
    "confirmPasswordLabel": "تأكيد كلمة المرور",
    "recaptchaError": "خطأ في reCAPTCHA.",
    "recaptchaExpired": "انتهت صلاحية reCAPTCHA. الرجاء إعادة التحقق.",
    "recaptchaRequired": "الرجاء إكمال reCAPTCHA.",
    "registerSuccess": "تم التسجيل بنجاح! الرجاء التحقق من بريدك الإلكتروني لتفعيل الحساب.",
    "registerError": "فشل التسجيل. الرجاء المحاولة مرة أخرى.",
    "registerButton": "تسجيل",
    "loginPrompt": "هل لديك حساب بالفعل؟",
    "loginLink": "سجل الدخول من هنا",
    "loginTitle": "تسجيل الدخول إلى حسابك",
    "loginSuccess": "تم تسجيل الدخول بنجاح!",
    "loginError": "فشل تسجيل الدخول. الرجاء التحقق من بيانات الاعتماد الخاصة بك.",
    "forgotPassword": "هل نسيت كلمة المرور؟",
    "registerPrompt": "ليس لديك حساب؟",
    "registerLink": "سجل الآن",
    "forgotPasswordTitle": "نسيت كلمة المرور",
    "forgotPasswordInstructions": "أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.",
    "resetEmailSent": "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.",
    "resetEmailError": "فشل في إرسال بريد إعادة تعيين كلمة المرور.",
    "sendResetLink": "إرسال رابط إعادة التعيين",
    "loginNow": "العودة إلى تسجيل الدخول",
    "accountActivation": "تفعيل الحساب",
    "activationSuccess": "تم تفعيل حسابك بنجاح!",
    "activationError": "فشل تفعيل الحساب. الرابط غير صالح أو انتهت صلاحيته.",
    "tokenMissing": "رمز التفعيل مفقود أو غير صالح.",
    
    "registerSuccessEmailSent": "تم التسجيل بنجاح! يرجى التحقق من بريدك الإلكتروني لتفعيل الحساب.",
    "registrationCompleteTitle": "تم التسجيل بنجاح",
    "goToLogin": "العودة إلى تسجيل الدخول",
    "loginWelcome": "مرحبا بعودتك",
    "loginSuccessTitle": "تم تسجيل الدخول بنجاح",
  },
  "productDetailsPage": {
    "productDataNotFound": "لم يتم العثور على بيانات المنتج.",
    "notFound": "المنتج غير موجود.",
    "failedToLoad": "فشل تحميل المنتج. يرجى التحقق من اتصالك أو المحاولة مرة أخرى.",
    "productDataMissing": "بيانات المنتج مفقودة.",
    "quantity": "الكمية",
    "securePayment": "دفع آمن",
    "fastShipping": "شحن سريع",
    "qualityGuarantee": "ضمان الجودة",
    "productDescription": "وصف المنتج",
    "productImages": "صور المنتج",
    "continueShopping": "مواصلة التسوق",
  "specifications": "مواصفات المنتج",
  "availableOptions": "الخيارات المتاحة",
  "selectOption": "حدد الخيار",
  "productMedia": "وسائط المنتج",
  "selectMoreOptions": "حدد المزيد من الخيارات",
  "sizes":"المقاسات",
  "color":"اللون",
    "clearSelection":"حذف الحدث",
    "variantNotFound":"المنتج غير موجود.",
    "lowStockAlert": "تنبيه: المنتجات اوشكت علي النفاذ.",
      "outOfStock": "غير متوفر",
 
  },
  "cart": {
    "loginRequired": "يرجى تسجيل الدخول لإضافة المنتجات إلى سلتك.",
    "productAdded": "تمت اضافة المنتج لسلتك.",
    "productAddedSuccess": "تمت اضافة المنتج لسلتك.",
    "updateSuccess": "تم تحديث سلة التسوق.",
    "productRemovedSuccess": "تمت ازالة المنتج من سلتك.",
  },
  "wishlist": {
    "loginRequired": "يرجى تسجيل الدخول للإضافة إلى المفضلة.",
    "addedToWishlist": "تمت اضافة المنتج لقائمة المفضلة."
  },
  "cartPage": {
    "shoppingCart": "سلة التسوق",
    "cartEmpty": "سلتك فارغة!",
    "cartEmptyDesc": "يبدو أنك لم تقم بإضافة أي شيء إلى سلتك بعد.",
    "continueShopping": "مواصلة التسوق",
    "removeItem": "إزالة العنصر",
    "cartTotal": "إجمالي السلة",
    "proceedToCheckout": "المتابعة للدفع",
    "cartEmptyCheckout": "سلتك فارغة. أضف عناصر قبل المتابعة للدفع.",
    "stockStatus": "حالة المستودع",
    "inStock": "في المستودع",
  },
  "checkoutPage": {
    "checkoutTitle": "إتمام عملية الشراء",
    "orderSummary": "ملخص الطلب",
    "discountCode": "كود الخصم",
    "enterDiscountCodePlaceholder": "أدخل كود الخصم",
    "apply": "تطبيق",
    "remove": "إزالة",
    "invalidOrExpiredDiscount": "كود الخصم غير صالح أو منتهي الصلاحية.",
    "minOrderNotMet": "يتطلب الخصم طلباً بحد أدنى {amount}.",
    "discountAppliedSuccessfully": "تم تطبيق الخصم بنجاح!",
    "discountRemoved": "تمت إزالة الخصم.",
    "shippingAndPayment": "الشحن والدفع",
    "shippingAddress": "عنوان الشحن",
    "enterAddressPlaceholder": "أدخل العنوان",
    "enterCityPlaceholder": "أدخل المدينة",
    "enterPostalCodePlaceholder": "أدخل الرمز البريدي",
    "enterCountryPlaceholder": "أدخل الدولة",
    "paymentMethod": "طريقة الدفع",
    "cashOnDelivery": "الدفع عند الاستلام",
    "placeOrder": "تأكيد الطلب",
    "placingOrder": "جاري تأكيد الطلب...",
    "orderPlacedSuccessTitle": "تم تأكيد طلبك بنجاح!",
    "orderPlacedSuccessMessage": "شكراً لك على شرائك. سيتم إعادة توجيهك إلى الصفحة الرئيسية قريباً.",
    "redirecting": "جاري إعادة التوجيه...",
    "pleaseLoginToCheckout": "الرجاء تسجيل الدخول لإتمام عملية الشراء.",
    "shippingPaymentRequired": "الرجاء توفير عنوان الشحن وطريقة الدفع.",
    "discountInvalidOrder": "الخصم المطبق لم يعد صالحاً بسبب تغييرات في السلة. الرجاء مراجعة طلبك.",
    "discountInvalidated": "تم إبطال الخصم المطبق.",
    "orderPlacementFailed": "فشل في تأكيد الطلب.",
    "orderPlacementError": "خطأ في تأكيد الطلب"
  },
  "contactUsPage": {
    "title": "اتصل بنا",
    "description": "هل لديك أي أسئلة أو تحتاج إلى مساعدة؟ لا تتردد في التواصل معنا. فريقنا متاح لمساعدتك في أي استفسارات تتعلق بخدماتنا ودعمنا.",
    "yourName": "اسمك",
    "yourSubject": "الموضوع",
    "yourEmail": "بريدك الإلكتروني",
    "yourPhone": "رقم هاتفك",
    "yourMessage": "رسالتك",
    "submitMessage": "إرسال الرسالة",
    "successMessage": "تم إرسال رسالتك بنجاح! شكراً لك.",
    "errorMessage": "فشل في إرسال الرسالة. يرجى المحاولة مرة أخرى.",
    "apiError": "لم يتم تعريف عنوان API. الرجاء التأكد من ضبط REACT_APP_API_URL في ملف .env الخاص بالواجهة الأمامية وإعادة تشغيل الخادم.",
    "networkError": "حدث خطأ أثناء الإرسال. الرجاء التحقق من اتصالك بالشبكة أو سجلات الخادم."
  },
  "aboutUsPage": {
    "title": "تكنو إكسبرس - متجرك الإلكتروني المفضل",
    "commitment": "في تكنو إكسبرس، نلتزم بتقديم أحدث وأفضل المنتجات الإلكترونية. سواء كنت تبحث عن هواتف ذكية متطورة، أو أجهزة لابتوب عالية الأداء، أو إكسسوارات فاخرة، فإننا نقدم مجموعة واسعة من المنتجات عالية الجودة بأسعار لا تضاهى.",
    "belief": "نؤمن بتقديم تجربة تسوق استثنائية من خلال ضمان التوصيل السريع، خيارات الدفع الآمنة، وخدمة عملاء ممتازة. هدفنا هو جعل التسوق التكنولوجي بسيطاً، موثوقاً، وممتعاً للجميع.",
    "explore": "اكتشف مجموعتنا وابقَ على اطلاع بأحدث صيحات التكنولوجيا. رضاكم هو أولويتنا!",
    "imageAlt": "مصافحة ترمز للشراكة والثقة"
  },
  "allOffersPage": {
    "title": "جميع العروض المتاحة",
    "noOffers": "لا توجد عروض متاحة في الوقت الحالي.",
    "noOffersTitle": "لا توجد عروض!",
    "productNotLinked": "هذا العرض لا يرتبط بمنتج محدد."
  },
  "advertisementDetails": {
    "notFound": "الإعلان غير موجود.",
    "noDetails": "لم يتم العثور على تفاصيل الإعلان.",
    "noDetailsTitle": "لا توجد تفاصيل إعلان!",
    "originalPrice": "السعر الأصلي",
    "currentPrice": "السعر الحالي",
    "validity": "فترة الصلاحية",
    "goToOffer": "انتقل إلى العرض",
    "typeSlide": "عرض الشريحة الرئيسية",
    "typeSideOffer": "عرض جانبي",
    "typeWeeklyOffer": "صفقة الأسبوع",
    "typeOther": "عرض خاص",
    "priceDetails": "تفاصيل السعر"
  },
  "adminDashboardPage": {
    "dashboardTitle": "لوحة التحكم",
    "productManagement": "إدارة المنتجات",
    "categoryManagement": "إدارة الفئات",
    "orderManagement": "إدارة الطلبات",
    "userManagement": "إدارة المستخدمين",
    "advertisementManagement": "إدارة الإعلانات",
    "discountManagement": "إدارة الخصومات",
    "settings": "الإعدادات",
    "analytics": "التحليلات",
    "errorFetchingData": "فشل جلب بيانات لوحة التحكم.",
    "noDataAvailable": "لا توجد بيانات متاحة لعرض لوحة التحكم.",
    "noDataAvailableTitle": "لا توجد بيانات!",
    "totalRevenue": "إجمالي الإيرادات",
    "totalOrders": "إجمالي الطلبات",
    "totalProducts": "إجمالي المنتجات",
    "totalUsers": "إجمالي المستخدمين",
    "salesOverviewChartTitle": "نظرة عامة على المبيعات (آخر 6 أشهر)",
    "revenueLabel": "الإيرادات",
    "orderCountLabel": "عدد الطلبات",
    "noSalesData": "لا توجد بيانات مبيعات متاحة.",
    "topSellingProductsTitle": "أكثر المنتجات مبيعاً",
    "quantitySoldLabel": "الكمية المباعة",
    "itemsSoldLabel": "عناصر مباعة",
    "noTopProductsData": "لا توجد بيانات عن المنتجات الأكثر مبيعاً.",
    "categoryDistributionChartTitle": "توزيع الفئات",
    "items": "عناصر",
    "noCategoryData": "لا توجد بيانات للفئات متاحة.",
    "ordersByStatusTitle": "الطلبات حسب الحالة",
    "noOrderStatusData": "لا توجد بيانات لحالة الطلبات متاحة.",
    "userRegistrationTitle": "تسجيل المستخدمين بمرور الوقت",
    "usersRegisteredLabel": "المستخدمون المسجلون",
    "noUserRegistrationData": "لا توجد بيانات لتسجيل المستخدمين متاحة.",
    "recentOrdersTitle": "الطلبات الأخيرة",
    "orderId": "معرف الطلب",
    "date": "التاريخ",
    "customer": "العميل",
    "total": "الإجمالي",
    "status": "الحالة",
    "guestUser": "زائر",
    "noRecentOrders": "لا توجد طلبات حديثة متاحة.",
    "orderStatuses": {
      "pending": "معلق",
      "processing": "قيد المعالجة",
      "shipped": "تم الشحن",
      "delivered": "تم التسليم",
      "cancelled": "ملغى",
      "footerText": "لوحة تحكم تكنو إكسبرس. جميع الحقوق محفوظة."

    }
  },
  "adminProductsPage": {
    "title": "إدارة المنتجات",
    "addNewProduct": "إضافة منتج جديد",
    "productList": "قائمة المنتجات",
    "footerText": "لوحة تحكم تكنو إكسبرس. جميع الحقوق محفوظة."
  },
  "productAdmin": { // New section for product management
    "productNameEn": "اسم المنتج (الإنجليزية)",
    "productNameEnPlaceholder": "اسم المنتج بالإنجليزية",
    "productNameAr": "اسم المنتج (العربية)",
    "productNameArPlaceholder": "اسم المنتج بالعربية",
    "descriptionEn": "وصف المنتج (الإنجليزية)",
    "descriptionEnPlaceholder": "وصف المنتج بالإنجليزية",
    "descriptionAr": "وصف المنتج (العربية)",
    "descriptionArPlaceholder": "وصف المنتج بالعربية",
    "priceLabel": "سعر المنتج",
    "pricePlaceholder": "أدخل سعر المنتج",
    "categoryLabel": "الفئة (اختياري)",
    "categoryPlaceholder": "أدخل فئة المنتج",
    "subCategoryLabel": "الفئة الفرعية (اختياري)",
    "subCategoryPlaceholder": "أدخل الفئة الفرعية للمنتج",
    "imageLabel": "صورة المنتج",
    "nameAndPriceRequired": "اسم المنتج (الإنجليزية والعربية) والسعر مطلوبان.",
    "imageRequired": "صورة المنتج مطلوبة.",
    "addSuccess": "تم إضافة المنتج بنجاح!",
    "addError": "خطأ في إضافة المنتج",
    "submittingButton": "جاري الإضافة...",
    "addButton": "إضافة المنتج",
    "imageTable" : "صورة",
    "nameTable" : "اسم",
    "descriptionTable" : "وصف",
    "categoryTable" : "فئة",
    "subCategoryTable" : "فئة فرعية",
    "priceTable" : "سعر",
    "actionTable" : "عملية",
  //     "specificAttributes": "Specific Attributes",
  //  "productVariants": "Product Variants",
  //  "variant": "Variant",
  //  "variantOptions": "Variant Options",
  //  "addOption": "Add Option",
  //  "priceAdjustment": "Price Adjustment",
  //  "stock": "stock",
  //  "sku": "sku",
  //  "addVariant": "Add Variant",
  //  "mainImageLabel": "Main Image",
  // "additionalImagesLabel": "Additional Images",
  // "videosLabel": "Videos",
  // "selectOptionType": "Select Option Type",
  // "selectCategory": "Select Category",
  "specificAttributes": "خصائص خاصة",
  "productVariants": "منتجات مختلفة",
  "variant": "مختلف",
  "variantOptions": "خيارات المختلف",
  "addOption": "اضافة خيار",
  "priceAdjustment": "تعديل سعر",
  "stock": "المخزون",
  "sku": "SKU",
  "addVariant": "اضافة مختلف",
  "mainImageLabel": "صورة رئيسية",
  "additionalImagesLabel": "صور اضافية",
  "videosLabel": "فيديوهات",
  "selectOptionType": "حدد نوع الخيار",
  "selectCategory": "حدد الفئة",
  "SKU":"رمز فريد",
  "addNewProduct": "اضافة منتج جديد",
    
  }
},
en :{
  "general": {
    "loading": "Loading...",
    "error": "Error",
    "notApplicable": "N/A",
    "unnamedItem": "Unnamed Item",
    "priceNotAvailable": "Price N/A",
    "shopNow": "Shop Now",
    "currencySymbol": "$",
    "off": "OFF",
    "noImage": "No Image",
    "errorFetchingData": "Failed to fetch data. Please try again later.",
    "resetting": "Resetting...",
    "unnamedProduct": "Unnamed Product",
    "imageFailedToLoad": "Image failed to load",
    "noImageAvailable": "No Image Available",
    "currencyCode": "USD",
    "viewImage": "View Image",
    "thumbnail": "Thumbnail",
    "decreaseQuantity": "Decrease Quantity",
    "increaseQuantity": "Increase Quantity",
    "productQuantity": "Product Quantity",
    "subtotal": "Subtotal",
    "total": "Total",
    "inCartShort": "In Cart",
    "addToCartShort": "Add",
    "removeFromWishlist": "Remove from Wishlist",
    "addToWishlist": "Add to Wishlist",
    "description": "Description",
    "submitting": "Submitting...",
    "verifyHuman": "Please verify you are human.",
    "sending": "Sending...",
    "apiError": "API URL is not defined.",
    "view":"View",
    "pleaseWait": "Please wait...",
    "image":"image",
    "clear": "Clear",
  },
  "heroSection": {
    "bigSale": "Limited Time Offer",
    "price": "Price",
    "validFrom": "Valid From",
    "validUntil": "Valid Until",
    "installment": "Easy Installments",
    "weeklySale": "Weekly Flash Deals!",
    "weeklyDesc": "Unlock incredible savings on your favorite products! Get up to",
    "thisWeek": "for a limited time.",
    "allOffersTitle": "Discover All Offers!",
    "allOffersDesc": "Explore all available promotions and discounts in one place.",
    "noDataAvailable": "No exciting offers available right now."
  },
  "homepage": {
    "discountsTitle": "Exclusive Discount Codes",
    "discountCode": "Your Code",
    "copied": "Copied!",
    "shopByCategory": "Shop by Category",
    "loadingCategories": "Loading categories...",
    "categoryFetchError": "Failed to fetch categories. Please try again later.",
    "noCategoriesFound": "No categories found.",
    "categoryImageAlt": "Category Image",
    "unnamedCategory": "Unnamed Category",
    "trendingProductsTitle": "Trending Products",
    "trendingProductsDesc": "Discover our most popular products this week.",
    "noTrendingProductsFound": "No trending products found.",
    "trendingProductsDesc": "Discover our most popular products this week.",
  "off":"OFF",
    "copyCode": "Copy Code",
  },
  "advertisementAdmin": {
    "noDescription": "No description available."
  },
  "productCard": {
    "uncategorized": "Uncategorized",
    "viewProduct": "View Product",
    "addToCart": "Add to Cart",
    "inCart": "In Cart", 
    "addToFavorites": "Add to Favorites",
    "removeFromFavorites": "In Favorites",
    "viewProductError": "Cannot view product details: Product data is missing.",
    "addToFavoritesError": "Cannot add product to favorites: Product data is incomplete.",
    "addToCartError": "Cannot add product to cart: Product data is incomplete.",
    "specialOffer": "Special Offer",
    "variantUnavailable": "Variant Unavailable",
    "viewDetails": "View Details",
    "variationsAvailable": "Variations Available"
  
  },
  "features": {
    "freeShipping": "Free Shipping",
    "freeShippingDesc": "Free shipping on all orders over $100",
    "support247": "Support 24/7",
    "support247Desc": "Get help anytime you need it",
    "onlinePayment": "Online Payment",
    "onlinePaymentDesc": "Secure online payment options",
    "easyReturn": "Easy Return",
    "easyReturnDesc": "Hassle-free returns within 30 days"
  },
  "mainHeader": {
    "siteName": "TechXpress",
    "searchPlaceholder": "Search for products...",
    "hotline": "Hotline",
    "myWishlist": "My Wishlist",
    "myCart": "My Cart",
    "myProfile": "My Profile",
    "myAccount": "My Account",
    "loginRegister": "Login / Register",
    "login": "Login"
  },
  "topBar": {
    "languageArabic": "Arabic",
    "languageEnglish": "English",
    "home": "Home",
    "shop": "Shop",
    "aboutUs": "About Us",
    "contactUs": "Contact Us",
    "dashboard": "Dashboard",
    "helloUser": "Hello",
    "helloGuest": "Hello Guest",
    "logout": "Logout",
    "signIn": "Sign In",
    "register": "Register",
    "lightMode": "Light Mode",
    "darkMode": "Dark Mode"
  },
  "shopPage": {
    "filter": "Filter",
    "showFilters": "Show Filters",
    "filterByCategory": "Filter by Category",
    "filterBySubCategory": "Filter by Sub-Category",
    "priceRange": "Price Range",
    "filterByBrand": "Filter by Brand",
    "sortBy": "Sort by:",
    "popularity": "Popularity",
    "priceLowToHigh": "Price: Low to High",
    "priceHighToLow": "Price: High to Low",
    "nameAZ": "Name (A-Z)",
    "showingItems": "Showing",
    "items": "items",
    "noProductsFound": "No products found matching your criteria.",
    "errorFetchingProducts": "Failed to load products. Please check your connection or try again.",
    "resetFilters": "Reset Filters",
    "addToFavorites": "Add to Favorites",
        "filterByOption": "Filter by Option",
    "allOptions": "All Options",
    "removeFromFavorites": "Remove from Favorites",
    
  },
  "brands": {
    "All Brands": "All Brands",
     " Urban Threads": " Urban Threads",
    "Dash Athletics": "Dash Athletics",
    "TechGen": "TechGen",
  },
  "wishlistPage": {
    "loadingWishlist": "Loading wishlist...",
    "pleaseLogin": "Please log in to view your wishlist.",
    "emptyWishlist": "Your wishlist is currently empty. Start adding your favorite items!",
    "wishlistTitle": "My Wishlist",
    "loginRequiredTitle": "Access Denied",
    "emptyWishlistTitle": "Your Wishlist is Empty!"
  },
  "auth": {
    "resetPasswordTitle": "Reset Password",
    "tokenExpired": "Reset link is missing or invalid.",
    "tokenExpiredOrInvalid": "This link is invalid or has expired.",
    "passwordMismatch": "Passwords do not match.",
    "passwordResetSuccess": "Password has been reset successfully. You will be redirected to the login page.",
    "passwordResetError": "Failed to reset password.",
    "newPasswordLabel": "New Password",
    "confirmNewPasswordLabel": "Confirm New Password",
    "requestNewLink": "Request New Link",
    "resetPasswordButton": "Reset Password",
    "verifyingLink": "Verifying reset link...",
    "passwordMinLength": "Password must be at least 6 characters long.",
    "registerTitle": "Create Your Account",
    "nameLabel": "Full Name",
    "emailLabel": "Email Address",
    "passwordLabel": "Password",
    "confirmPasswordLabel": "Confirm Password",
    "recaptchaError": "reCAPTCHA error.",
    "recaptchaExpired": "reCAPTCHA expired. Please re-verify.",
    "recaptchaRequired": "Please complete the reCAPTCHA.",
    "registerSuccess": "Registration successful! Please check your email for activation link.",
    "registerError": "Registration failed. Please try again.",
    "registerButton": "Register",
    "loginPrompt": "Already have an account?",
    "loginLink": "Login here",
    "loginTitle": "Login to Your Account",
    "loginSuccess": "Login successful!",
    "loginError": "Login failed. Please check your credentials.",
    "forgotPassword": "Forgot Password?",
    "registerPrompt": "Don’t have an account?",
    "registerLink": "Sign up here",
    "forgotPasswordTitle": "Forgot Password",
    "forgotPasswordInstructions": "Enter your email address and we'll send you a link to reset your password.",
    "resetEmailSent": "Password reset link sent to your email.",
    "resetEmailError": "Failed to send password reset email.",
    "sendResetLink": "Send Reset Link",
    "loginNow": "Back to Login",
    "accountActivation": "Account Activation",
    "activationSuccess": "Your account has been activated successfully!",
    "activationError": "Account activation failed. The link is invalid or has expired.",
    "tokenMissing": "Activation token is missing or invalid.",
    "registerSuccessEmailSent": "Registration successful! Please check your email for activation link.",
    "registrationCompleteTitle": "Registration Complete",
    "goToLogin": "Go to Login",
    "loginWelcome": "Welcome Back",
    "loginSuccessTitle": "Login Successful",
  },
  "productDetailsPage": {
    "productDataNotFound": "Product data not found.",
    "notFound": "Product not found.",
    "failedToLoad": "Failed to load product. Please check your connection or try again.",
    "productDataMissing": "Product data is missing.",
    "quantity": "Quantity",
    "securePayment": "Secure Payment",
    "fastShipping": "Fast Shipping",
    "qualityGuarantee": "Quality Guarantee",
    "productDescription": "Product Description",
    "productImages": "Product Images",
    "continueShopping": "Continue Shopping",
    "productMedia": "Product Media",
     "selectMoreOptions": "Select more options",
  "sizes":"sizes",
  "color":"color",
  "clearSelection":"clear selection",
  "variantNotFound":"variant not found",
    "lowStockAlert": "Low stock alert",
    "outOfStock": "Out of stock",
 



  },
  "cart": {
    "loginRequired": "Please log in to add products to your cart.",
    "productAdded": "Product added to cart successfully.",
    "productAddedSuccess": "Product added to cart successfully.",
    "updateSuccess": "Cart updated successfully.",
    "productRemovedSuccess": "Product removed from cart successfully.",
  },
  "wishlist": {
    "loginRequired": "Please log in to add to favorites.",
    "addedToWishlist":"the product has been added to your wishlist."
  },
  "cartPage": {
    "shoppingCart": "Shopping Cart",
    "cartEmpty": "Your cart is empty!",
    "cartEmptyDesc": "Looks like you haven't added anything to your cart yet.",
    "continueShopping": "Continue Shopping",
    "removeItem": "Remove Item",
    "cartTotal": "Cart Total",
    "proceedToCheckout": "Proceed to Checkout",
    "cartEmptyCheckout": "Your cart is empty. Add items before checking out.",
    "stockStatus": "Stock Status",
    "inStock": "In Stock",
  },
  "checkoutPage": {
    "checkoutTitle": "Checkout",
    "orderSummary": "Order Summary",
    "discountCode": "Discount Code",
    "enterDiscountCodePlaceholder": "Enter discount code",
    "apply": "Apply",
    "remove": "Remove",
    "invalidOrExpiredDiscount": "Invalid or expired discount code.",
    "minOrderNotMet": "Discount requires a minimum order of {amount}.",
    "discountAppliedSuccessfully": "Discount applied successfully!",
    "discountRemoved": "Discount removed.",
    "shippingAndPayment": "Shipping & Payment",
    "shippingAddress": "Shipping Address",
    "enterAddressPlaceholder": "Enter Address",
    "enterCityPlaceholder": "Enter City",
    "enterPostalCodePlaceholder": "Enter Postal Code",
    "enterCountryPlaceholder": "Enter Country",
    "paymentMethod": "Payment Method",
    "cashOnDelivery": "Cash on Delivery",
    "placeOrder": "Place Order",
    "placingOrder": "Placing Order...",
    "orderPlacedSuccessTitle": "Order Placed Successfully!",
    "orderPlacedSuccessMessage": "Thank you for your purchase. You will be redirected to the home page shortly.",
    "redirecting": "Redirecting...",
    "pleaseLoginToCheckout": "Please log in to checkout.",
    "shippingPaymentRequired": "Please provide shipping address and payment method.",
    "discountInvalidOrder": "The applied discount is no longer valid due to cart changes. Please review your order.",
    "discountInvalidated": "Applied discount became invalid.",
    "orderPlacementFailed": "Order placement failed.",
    "orderPlacementError": "Error placing order"
  },
  "contactUsPage": {
    "title": "Contact Us",
    "description": "Have any questions or need assistance? Feel free to reach out to us. Our team is available to help you with any inquiries regarding our services and support.",
    "yourName": "Your Name",
    "yourSubject": "Your Subject",
    "yourEmail": "Your Email",
    "yourPhone": "Your Phone",
    "yourMessage": "Your Message",
    "submitMessage": "Submit Message",
    "successMessage": "Message submitted successfully! Thank you.",
    "errorMessage": "Failed to submit message. Please try again.",
    "apiError": "API URL is not defined. Please ensure REACT_APP_API_URL is set in your frontend .env file and restart the development server.",
    "networkError": "An error occurred during submission. Please check your network connection or server logs."
  },
  "aboutUsPage": {
    "title": "تكنو إكسبرس - متجرك الإلكتروني المفضل",
    "commitment": "في تكنو إكسبرس، نلتزم بتقديم أحدث وأفضل المنتجات الإلكترونية. سواء كنت تبحث عن هواتف ذكية متطورة، أو أجهزة لابتوب عالية الأداء، أو إكسسوارات فاخرة، فإننا نقدم مجموعة واسعة من المنتجات عالية الجودة بأسعار لا تضاهى.",
    "belief": "نؤمن بتقديم تجربة تسوق استثنائية من خلال ضمان التوصيل السريع، خيارات الدفع الآمنة، وخدمة عملاء ممتازة. هدفنا هو جعل التسوق التكنولوجي بسيطاً، موثوقاً، وممتعاً للجميع.",
    "explore": "اكتشف مجموعتنا وابقَ على اطلاع بأحدث صيحات التكنولوجيا. رضاكم هو أولويتنا!",
    "imageAlt": "مصافحة ترمز للشراكة والثقة"
  },
  "allOffersPage": {
    "title": "جميع العروض المتاحة",
    "noOffers": "لا توجد عروض متاحة في الوقت الحالي.",
    "noOffersTitle": "لا توجد عروض!",
    "productNotLinked": "هذا العرض لا يرتبط بمنتج محدد."
  },
  "advertisementDetails": {
    "notFound": "الإعلان غير موجود.",
    "noDetails": "لم يتم العثور على تفاصيل الإعلان.",
    "noDetailsTitle": "لا توجد تفاصيل إعلان!",
    "originalPrice": "السعر الأصلي",
    "currentPrice": "السعر الحالي",
    "validity": "فترة الصلاحية",
    "goToOffer": "انتقل إلى العرض",
    "typeSlide": "عرض الشريحة الرئيسية",
    "typeSideOffer": "عرض جانبي",
    "typeWeeklyOffer": "صفقة الأسبوع",
    "typeOther": "عرض خاص",
    "priceDetails": "تفاصيل السعر"
  },
  "adminDashboardPage": {
    "dashboardTitle": "لوحة التحكم",
    "productManagement": "إدارة المنتجات",
    "categoryManagement": "إدارة الفئات",
    "orderManagement": "إدارة الطلبات",
    "userManagement": "إدارة المستخدمين",
    "advertisementManagement": "إدارة الإعلانات",
    "discountManagement": "إدارة الخصومات",
    "settings": "الإعدادات",
    "analytics": "التحليلات",
    "errorFetchingData": "فشل جلب بيانات لوحة التحكم.",
    "noDataAvailable": "لا توجد بيانات متاحة لعرض لوحة التحكم.",
    "noDataAvailableTitle": "لا توجد بيانات!",
    "totalRevenue": "إجمالي الإيرادات",
    "totalOrders": "إجمالي الطلبات",
    "totalProducts": "إجمالي المنتجات",
    "totalUsers": "إجمالي المستخدمين",
    "salesOverviewChartTitle": "نظرة عامة على المبيعات (آخر 6 أشهر)",
    "revenueLabel": "الإيرادات",
    "orderCountLabel": "عدد الطلبات",
    "noSalesData": "لا توجد بيانات مبيعات متاحة.",
    "topSellingProductsTitle": "أكثر المنتجات مبيعاً",
    "quantitySoldLabel": "الكمية المباعة",
    "itemsSoldLabel": "عناصر مباعة",
    "noTopProductsData": "لا توجد بيانات عن المنتجات الأكثر مبيعاً.",
    "categoryDistributionChartTitle": "توزيع الفئات",
    "items": "عناصر",
    "noCategoryData": "لا توجد بيانات للفئات متاحة.",
    "ordersByStatusTitle": "الطلبات حسب الحالة",
    "noOrderStatusData": "لا توجد بيانات لحالة الطلبات متاحة.",
    "userRegistrationTitle": "تسجيل المستخدمين بمرور الوقت",
    "usersRegisteredLabel": "المستخدمون المسجلون",
    "noUserRegistrationData": "لا توجد بيانات لتسجيل المستخدمين متاحة.",
    "recentOrdersTitle": "الطلبات الأخيرة",
    "orderId": "معرف الطلب",
    "date": "التاريخ",
    "customer": "العميل",
    "total": "الإجمالي",
    "status": "الحالة",
    "guestUser": "زائر",
    "noRecentOrders": "لا توجد طلبات حديثة متاحة.",
    "orderStatuses": {
      "pending": "معلق",
      "processing": "قيد المعالجة",
      "shipped": "تم الشحن",
      "delivered": "تم التسليم",
      "cancelled": "ملغى",
      "footerText": "لوحة تحكم تكنو إكسبرس. جميع الحقوق محفوظة."
    },
    "imageTable" : "صورة",
  },
  "adminProductsPage": {
    "title": "إدارة المنتجات",
    "addNewProduct": "إضافة منتج جديد",
    "productList": "قائمة المنتجات",
    "footerText": "لوحة تحكم تكنو إكسبرس. جميع الحقوق محفوظة."
  },
  "productAdmin": {
    "productNameEn": "اسم المنتج (الإنجليزية)",
    "productNameEnPlaceholder": "اسم المنتج بالإنجليزية",
    "productNameAr": "اسم المنتج (العربية)",
    "productNameArPlaceholder": "اسم المنتج بالعربية",
    "descriptionEn": "وصف المنتج (الإنجليزية)",
    "descriptionEnPlaceholder": "وصف المنتج بالإنجليزية",
    "descriptionAr": "وصف المنتج (العربية)",
    "descriptionArPlaceholder": "وصف المنتج بالعربية",
    "priceLabel": "سعر المنتج",
    "pricePlaceholder": "أدخل سعر المنتج",
    "categoryLabel": "الفئة (اختياري)",
    "categoryPlaceholder": "أدخل فئة المنتج",
    "subCategoryLabel": "الفئة الفرعية (اختياري)",
    "subCategoryPlaceholder": "أدخل الفئة الفرعية للمنتج",
    "imageLabel": "صورة المنتج",
    "nameAndPriceRequired": "اسم المنتج (الإنجليزية والعربية) والسعر مطلوبان.",
    "imageRequired": "صورة المنتج مطلوبة.",
    "addSuccess": "تم إضافة المنتج بنجاح!",
    "addError": "خطأ في إضافة المنتج",
    "submittingButton": "جاري الإضافة...",
    "addButton": "إضافة المنتج",
        "actionsTable" : "Action",
    "noSubCategory": "No subcategory found.",
    "addProductButton": "Add Product",
    "addNewProduct": "Add New Product",
    "editProductTitle": "Edit Product",
    "confirmDelete" : "Are you sure you want to delete this product? This action cannot be undone.",
    "deleteSuccess" : "Product deleted successfully!",
    "updateButton": "Update Product",
    "cancelButton":"cancel",
    "imageOptional": "Image (Optional)",
  },
  "adminCategoryPage" :{
    categoryListTitle : "قائمة الفئات",
    confirmDelete : "Are you sure you want to delete this category? This action cannot be undone.",

  }
},
en :{
  "general": {
    "loading": "Loading...",
    "error": "Error",
    "notApplicable": "N/A",
    "unnamedItem": "Unnamed Item",
    "priceNotAvailable": "Price N/A",
    "shopNow": "Shop Now",
    "currencySymbol": "$",
    "off": "OFF",
    "noImage": "No Image",
    "errorFetchingData": "Failed to fetch data. Please try again later.",
    "resetting": "Resetting...",
    "unnamedProduct": "Unnamed Product",
    "imageFailedToLoad": "Image failed to load",
    "noImageAvailable": "No Image Available",
    "currencyCode": "USD",
    "viewImage": "View Image",
    "thumbnail": "Thumbnail",
    "decreaseQuantity": "Decrease Quantity",
    "increaseQuantity": "Increase Quantity",
    "productQuantity": "Product Quantity",
    "subtotal": "Subtotal",
    "total": "Total",
    "inCartShort": "In Cart",
    "addToCartShort": "Add",
    "removeFromWishlist": "Remove from Wishlist",
    "addToWishlist": "Add to Wishlist",
    "description": "Description",
    "submitting": "Submitting...",
    "verifyHuman": "Please verify you are human.",
    "sending": "Sending...",
    "apiError": "API URL is not defined.",
    "view":"View",
    "pleaseWait":"Please wait...",
    "image":"image",
    "clear":"clear",
  },
  "heroSection": {
    "bigSale": "Limited Time Offer",
    "price": "Price",
    "validFrom": "Valid From",
    "validUntil": "Valid Until",
    "installment": "Easy Installments",
    "weeklySale": "Weekly Flash Deals!",
    "weeklyDesc": "Unlock incredible savings on your favorite products! Get up to",
    "thisWeek": "for a limited time.",
    "allOffersTitle": "Discover All Offers!",
    "allOffersDesc": "Explore all available promotions and discounts in one place.",
    "noDataAvailable": "No exciting offers available right now."
  },
  "homepage": {
    "discountsTitle": "Exclusive Discount Codes",
    "discountCode": "Your Code",
    "copied": "Copied!",
    "shopByCategory": "Shop by Category",
    "loadingCategories": "Loading categories...",
    "categoryFetchError": "Failed to fetch categories. Please try again later.",
    "noCategoriesFound": "No categories found.",
    "categoryImageAlt": "Category Image",
    "unnamedCategory": "Unnamed Category",
    "trendingProductsTitle": "Trending Products",
    "trendingProductsDesc": "Discover our most popular products this week.",
    "noTrendingProductsFound": "No trending products found.",
    "off":"OFF",
    "copyCode": "Copy Code",
  },
  "advertisementAdmin": {
    "noDescription": "No description available."
  },
  "productCard": {
    "uncategorized": "Uncategorized",
    "viewProduct": "View Product",
    "addToCart": "Add to Cart",
    "inCart": "In Cart", 
    "addToFavorites": "Add to Favorites",
    "removeFromFavorites": "In Favorites",
    "viewProductError": "Cannot view product details: Product data is missing.",
    "addToFavoritesError": "Cannot add product to favorites: Product data is incomplete.",
    "addToCartError": "Cannot add product to cart: Product data is incomplete.",
    "specialOffer": "Special Offer",
    "viewDetails": "View Details",
    "variationsAvailable": "Variations Available",
  },
  "features": {
    "freeShipping": "Free Shipping",
    "freeShippingDesc": "Free shipping on all orders over $100",
    "support247": "Support 24/7",
    "support247Desc": "Get help anytime you need it",
    "onlinePayment": "Online Payment",
    "onlinePaymentDesc": "Secure online payment options",
    "easyReturn": "Easy Return",
    "easyReturnDesc": "Hassle-free returns within 30 days"
  },
  "mainHeader": {
    "siteName": "TechXpress",
    "searchPlaceholder": "Search for products...",
    "hotline": "Hotline",
    "myWishlist": "My Wishlist",
    "myCart": "My Cart",
    "myProfile": "My Profile",
    "myAccount": "My Account",
    "loginRegister": "Login / Register",
    "login": "Login"
  },
  "topBar": {
    "languageArabic": "Arabic",
    "languageEnglish": "English",
    "home": "Home",
    "shop": "Shop",
    "aboutUs": "About Us",
    "contactUs": "Contact Us",
    "dashboard": "Dashboard",
    "helloUser": "Hello",
    "helloGuest": "Hello Guest",
    "logout": "Logout",
    "signIn": "Sign In",
    "register": "Register",
    "lightMode": "Light Mode",
    "darkMode": "Dark Mode"
  },
  "shopPage": {
    "filter": "Filter",
    "showFilters": "Show Filters",
    "filterByCategory": "Filter by Category",
    "filterBySubCategory": "Filter by Sub-Category",
    "priceRange": "Price Range",
    "filterByBrand": "Filter by Brand",
    "sortBy": "Sort by:",
    "popularity": "Popularity",
    "priceLowToHigh": "Price: Low to High",
    "priceHighToLow": "Price: High to Low",
    "nameAZ": "Name (A-Z)",
    "showingItems": "Showing",
    "items": "items",
    "noProductsFound": "No products found matching your criteria.",
    "errorFetchingProducts": "Failed to load products. Please check your connection or try again.",
    "currencySymbol": "$",
    "addToCart": "Add to Cart",
    "currencyCode": "SAR",
    "resetFilters": "Reset Filters",
    "allSubcategories": "All Subcategories",
    "addToFavorites": "Add to Favorites",
        "filterByOption": "Filter by Option",
    "allOptions": "All Options",
    "removeFromFavorites": "Remove from Favorites",

  },
  "brands": {
    "All Brands": "All Brands",
    "Nike": "Nike",
    " Urban Threads": " Urban Threads",
    "Dash Athletics": "Dash Athletics",
    "TechGen": "TechGen",
  },
  "wishlistPage": {
    "loadingWishlist": "Loading wishlist...",
    "pleaseLogin": "Please log in to view your wishlist.",
    "emptyWishlist": "Your wishlist is currently empty. Start adding your favorite items!",
    "wishlistTitle": "My Wishlist",
    "loginRequiredTitle": "Access Denied",
    "emptyWishlistTitle": "Your Wishlist is Empty!"
  },
  "auth": {
    "resetPasswordTitle": "Reset Password",
    "tokenExpired": "Reset link is missing or invalid.",
    "tokenExpiredOrInvalid": "This link is invalid or has expired.",
    "passwordMismatch": "Passwords do not match.",
    "passwordResetSuccess": "Password has been reset successfully. You will be redirected to the login page.",
    "passwordResetError": "Failed to reset password.",
    "newPasswordLabel": "New Password",
    "confirmNewPasswordLabel": "Confirm New Password",
    "requestNewLink": "Request New Link",
    "resetPasswordButton": "Reset Password",
    "verifyingLink": "Verifying reset link...",
    "passwordMinLength": "Password must be at least 6 characters long.",
    "registerTitle": "Create Your Account",
    "nameLabel": "Full Name",
    "emailLabel": "Email Address",
    "passwordLabel": "Password",
    "confirmPasswordLabel": "Confirm Password",
    "recaptchaError": "reCAPTCHA error.",
    "recaptchaExpired": "reCAPTCHA expired. Please re-verify.",
    "recaptchaRequired": "Please complete the reCAPTCHA.",
    "registerSuccess": "Registration successful! Please check your email for activation link.",
    "registerError": "Registration failed. Please try again.",
    "registerButton": "Register",
    "loginPrompt": "Already have an account?",
    "loginLink": "Login here",
    "loginTitle": "Login to Your Account",
    "loginSuccess": "Login successful!",
    "loginError": "Login failed. Please check your credentials.",
    "forgotPassword": "Forgot Password?",
    "registerPrompt": "Don’t have an account?",
    "registerLink": "Sign up here",
    "forgotPasswordTitle": "Forgot Password",
    "forgotPasswordInstructions": "Enter your email address and we'll send you a link to reset your password.",
    "resetEmailSent": "Password reset link sent to your email.",
    "resetEmailError": "Failed to send password reset email.",
    "sendResetLink": "Send Reset Link",
    "loginNow": "Back to Login",
    "accountActivation": "Account Activation",
    "activationSuccess": "Your account has been activated successfully!",
    "activationError": "Account activation failed. The link is invalid or has expired.",
    "tokenMissing": "Activation token is missing or invalid.",
    "registerSuccessEmailSent": "Registration successful! Please check your email for activation link.",
    "registrationCompleteTitle": "Registration Complete",
    "goToLogin": "Go to Login",
    "loginButton": "Login",
    "loginWelcome": "Welcome Back",
    "loginSuccessTitle": "Login Successful",
  },
  "productDetailsPage": {
    "productDataNotFound": "Product data not found.",
    "notFound": "Product not found.",
    "failedToLoad": "Failed to load product. Please check your connection or try again.",
    "productDataMissing": "Product data is missing.",
    "quantity": "Quantity",
    "securePayment": "Secure Payment",
    "fastShipping": "Fast Shipping",
    "qualityGuarantee": "Quality Guarantee",
    "productDescription": "Product Description",
    "productImages": "Product Images",
    "continueShopping": "Continue Shopping",
    "specifications": "Specifications",
    "availableOptions": "Available Options",
    "selectOption": "Select Option",
    "productMedia": "Product Media",
    "selectMoreOptions": "حدد المزيد من الخيارات",
    "sizes":"sizes",
    "color":"color",
      "clearSelection":"clear selection",
        "outOfStock": "Out of stock",
        "variantNotFound": "variant not found",
  },
  "cart": {
    "loginRequired": "Please log in to add products to your cart.",
    "productAdded": "Product added to cart.",
    "productAddedSuccess": "Product added to cart successfully.",
    "updateSuccess": "Cart updated successfully.",
    "productRemovedSuccess": "Product removed from cart successfully.",
  },
  "wishlist": {
    "loginRequired": "Please log in to add to favorites."
  },
  "cartPage": {
    "shoppingCart": "Shopping Cart",
    "cartEmpty": "Your cart is empty!",
    "cartEmptyDesc": "Looks like you haven't added anything to your cart yet.",
    "continueShopping": "Continue Shopping",
    "removeItem": "Remove Item",
    "cartTotal": "Cart Total",
    "proceedToCheckout": "Proceed to Checkout",
    "cartEmptyCheckout": "Your cart is empty. Add items before checking out.",
    "stockStatus": "Stock Status",
    "inStock": "In Stock",
  },
  "checkoutPage": {
    "checkoutTitle": "Checkout",
    "orderSummary": "Order Summary",
    "discountCode": "Discount Code",
    "enterDiscountCodePlaceholder": "Enter discount code",
    "apply": "Apply",
    "remove": "Remove",
    "invalidOrExpiredDiscount": "Invalid or expired discount code.",
    "minOrderNotMet": "Discount requires a minimum order of {amount}.",
    "discountAppliedSuccessfully": "Discount applied successfully!",
    "discountRemoved": "Discount removed.",
    "shippingAndPayment": "Shipping & Payment",
    "shippingAddress": "Shipping Address",
    "enterAddressPlaceholder": "Enter Address",
    "enterCityPlaceholder": "Enter City",
    "enterPostalCodePlaceholder": "Enter Postal Code",
    "enterCountryPlaceholder": "Enter Country",
    "paymentMethod": "Payment Method",
    "cashOnDelivery": "Cash on Delivery",
    "placeOrder": "Place Order",
    "placingOrder": "Placing Order...",
    "orderPlacedSuccessTitle": "Order Placed Successfully!",
    "orderPlacedSuccessMessage": "Thank you for your purchase. You will be redirected to the home page shortly.",
    "redirecting": "Redirecting...",
    "pleaseLoginToCheckout": "Please log in to checkout.",
    "shippingPaymentRequired": "Please provide shipping address and payment method.",
    "discountInvalidOrder": "The applied discount is no longer valid due to cart changes. Please review your order.",
    "discountInvalidated": "Applied discount became invalid.",
    "orderPlacementFailed": "Order placement failed.",
    "orderPlacementError": "Error placing order"
  },
  "contactUsPage": {
    "title": "Contact Us",
    "description": "Have any questions or need assistance? Feel free to reach out to us. Our team is available to help you with any inquiries regarding our services and support.",
    "yourName": "Your Name",
    "yourSubject": "Your Subject",
    "yourEmail": "Your Email",
    "yourPhone": "Your Phone",
    "yourMessage": "Your Message",
    "submitMessage": "Submit Message",
    "successMessage": "Message submitted successfully! Thank you.",
    "errorMessage": "Failed to submit message. Please try again.",
    "apiError": "API URL is not defined. Please ensure REACT_APP_API_URL is set in your frontend .env file and restart the development server.",
    "networkError": "An error occurred during submission. Please check your network connection or server logs."
  },
  "aboutUsPage": {
    "title": "TechXpress - Your Go-To Electronics Store",
    "commitment": "At TechXpress, we are committed to bringing you the latest and greatest in electronics. Whether you’re looking for cutting-edge smartphones, high-performance laptops, or premium accessories, we offer a wide selection of top-quality products at unbeatable prices.",
    "belief": "We believe in providing an exceptional shopping experience by ensuring fast delivery, secure payment options and outstanding customer service. Our goal is to make tech shopping simple, reliable, and enjoyable for everyone.",
    "explore": "Explore our collection and stay ahead with the latest technology trends. Your satisfaction is our priority!",
    "imageAlt": "Handshake representing partnership and trust"
  },
  "allOffersPage": {
    "title": "All Available Offers",
    "noOffers": "No offers are available at the moment.",
    "noOffersTitle": "No Offers Available!",
    "productNotLinked": "This offer is not linked to a specific product."
  },
  "advertisementDetails": {
    "notFound": "Advertisement not found.",
    "noDetails": "No advertisement details found.",
    "noDetailsTitle": "No Advertisement Details!",
    "originalPrice": "Original Price",
    "currentPrice": "Current Price",
    "validity": "Validity Period",
    "goToOffer": "Go To Offer",
    "typeSlide": "Main Carousel Offer",
    "typeSideOffer": "Side Offer",
    "typeWeeklyOffer": "Weekly Deal",
    "typeOther": "Special Offer",
    "priceDetails": "Price Details"
  },
  "adminDashboardPage": {
    "dashboardTitle": "Dashboard",
    "productManagement": "Products",
    "categoryManagement": "Categories",
    "orderManagement": "Orders",
    "userManagement": "Users",
    "advertisementManagement": "Advertisements",
    "discountManagement": "Discounts",
    "settings": "Settings",
    "analytics": "Analytics",
    "errorFetchingData": "Failed to fetch dashboard data.",
    "noDataAvailable": "No data available to display dashboard.",
    "noDataAvailableTitle": "No Data Available!",
    "totalRevenue": "Total Revenue",
    "totalOrders": "Total Orders",
    "totalProducts": "Total Products",
    "totalUsers": "Total Users",
    "salesOverviewChartTitle": "Sales Overview (Last 6 Months)",
    "revenueLabel": "Revenue",
    "orderCountLabel": "Order Count",
    "noSalesData": "No sales data available.",
    "topSellingProductsTitle": "Top Selling Products",
    "quantitySoldLabel": "Quantity Sold",
    "itemsSoldLabel": "items sold",
    "noTopProductsData": "No top selling products data available.",
    "categoryDistributionChartTitle": "Category Distribution",
    "items": "items",
    "noCategoryData": "No category data available.",
    "ordersByStatusTitle": "Orders by Status",
    "noOrderStatusData": "No order status data available.",
    "userRegistrationTitle": "User Registration Over Time",
    "usersRegisteredLabel": "Users Registered",
    "noUserRegistrationData": "No user registration data available.",
    "recentOrdersTitle": "Recent Orders",
    "orderId": "Order ID",
    "date": "Date",
    "customer": "Customer",
    "total": "Total",
    "status": "Status",
    "guestUser": "Guest User",
    "noRecentOrders": "No recent orders available.",
    "orderStatuses": {
      "pending": "Pending",
      "processing": "Processing",
      "shipped": "Shipped",
      "delivered": "Delivered",
      "cancelled": "Cancelled"
    }
  },
  "adminProductsPage": {
    "title": "Product Management",
    "addNewProduct": "Add New Product",
    "productList": "Product List",
    "footerText": "TechXpress Admin. All rights reserved."
  },
  "productAdmin": {
    "productNameEn": "Product Name (English)",
    "productNameEnPlaceholder": "Enter product name in English",
    "productNameAr": "Product Name (Arabic)",
    "productNameArPlaceholder": "Enter product name in Arabic",
    "descriptionEn": "Product Description (English)",
    "descriptionEnPlaceholder": "Enter product description in English",
    "descriptionAr": "Product Description (Arabic)",
    "descriptionArPlaceholder": "Enter product description in Arabic",
    "priceLabel": "Product Price",
    "pricePlaceholder": "Enter product price",
    "categoryLabel": "Category (Optional)",
    "categoryPlaceholder": "Enter product category",
    "subCategoryLabel": "Sub-Category (Optional)",
    "subCategoryPlaceholder": "Enter product sub-category",
    "imageLabel": "Product Image",
    "nameAndPriceRequired": "Product English and Arabic names, and price are required.",
    "imageRequired": "Product image is required.",
    "addSuccess": "Product added successfully!",
    "addError": "Error adding product",
    "submittingButton": "Adding...",
    "addButton": "Add Product",
    "imageTable" : "Image",
    "nameTable" : "Name",
    "descriptionTable" : "Description",
    "categoryTable" : "Category",
    "subCategoryTable" : "Sub-Category",
    "priceTable" : "Price",
    "actionsTable" : "Action",
    "noSubCategory": "No subcategory found.",
    "addProductButton": "Add Product",
    "addNewProduct": "Add New Product",
    "editProductTitle": "Edit Product",
    "confirmDelete" : "Are you sure you want to delete this product? This action cannot be undone.",
    "deleteSuccess" : "Product deleted successfully!",
    "updateButton": "Update Product",
    "cancelButton":"cancel",
    "imageOptional": "Image (Optional)",
   "specificAttributes": "Specific Attributes",
   "productVariants": "Product Variants",
   "variant": "Variant",
   "variantOptions": "Variant Options",
   "addOption": "Add Option",
   "priceAdjustment": "Price Adjustment",
   "stock": "stock",
   "sku": "sku",
   "addVariant": "Add Variant",
   "mainImageLabel": "Main Image",
  "additionalImagesLabel": "Additional Images",
  "videosLabel": "Videos",
  "selectOptionType": "Select Option Type",
  "selectCategory": "Select Category",
  },
  "adminCategoryPage":{
    "categoryListTitle" :"All Categories",
    "addCategoryButton" : "Add Category",
    "noDescription": "No description available.",

  },
  "adminOrdersPage" :{
    "allOrders" : "All Orders",
    "orderID" : "Order ID",
    "user" : "User",
    "date" : "Date",
    "total" : "Total",
    "paid" :"Paid",
    "delivered":"Delivered",
    "yes" :"Yes",
    "no" :"No",
    "details" :"Details",
    "orderDetails":"order Details",
    "shippingAddress":"Shipping Address",
    "paymentMethod" : "payment Method",
    "address" :"address",
    "status" :"Status",
    "method" :"Method",
    "orderItems" :"Order Items",
    "customerInfo" :"Customer Info",
    "name" :"Name",
    "email":"Email",
    "orderSummary" :"Order Summary",
    "itemsPrice" :"Items Price",
    "shippingPrice" :"Shipping Price",
   "taxPrice" :"Tax Price",
   "totalPrice" :"Total Price",
   "dates" :"Dates",
   "orderedAt" :"Ordered At",
   "deliveredAt" :"Delivered At",
   "noOrderData" :"No order data available.",
   "paidAt" :"Paid At",
 
  },
  "advertisementAdmin":{
    "advertisementListTitle" :"All Advertisements",
    "addAdvertisementButton" : "Add Advertisement",
    "imageTable" : "Image",
    "titleTable" : "Title",
    "descriptionTable" : "Description",
    "typeTable" : "Type",
    "startDate" :"start Date",

    "noDescription": "No description available.",
    "endDate":"End Date",
    "originalPrice":"original price",
    "discountedPrice" :"Discount Price",
    "currency":"Currency",
    "activeTable":"Active",
    "orderTable":"Order",
    "actionsTable":"Actions",
    "titleEn":"Title (English)",
    "titleAr":"Title (Arabic)",
    "descriptionEn":"description (English)",
    "descriptionAr":"description (Arabic)",
    "linkLabel":"Link",
    "typeLabel":"Type",
    "orderLabel":"Order",
    "isActive":"Active",
    "imageLabel":"Image",
    "addButton": "add",
    "editAdvertisementTitle": "Edit Advertisement",
    "imageOptional": "Image (Optional)",
    "updateButton": "Update Advertisement",
    "confirmDelete":"Are you sure you want to delete this advertisement? This action cannot be undone.",


  },
  "discountAdmin":{
    "discountListTitle" :"All Discounts",
    "codeTable" : "Code",
    "typeTable" : "Type",
    "valueTable" : "Value",
    "minOrderTable" : "Min Order",
    "maxDiscountTable" : "Max Order",
    "startDateTable" : "Start Date",
    "endDateTable" : "End Date",
    "activeTable" : "Active",
    "actionsTable" : "Actions",
    "addDiscountButton" : "Add Discount",
    "codeLabel":"Code",
    

  }
}
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const savedLanguage = localStorage.getItem('appLanguage');
        return savedLanguage || 'en';
    });

    useEffect(() => {
        localStorage.setItem('appLanguage', language);
        document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prevLanguage => (prevLanguage === 'en' ? 'ar' : 'en'));
    };

    const changeLanguage = (newLanguage) => {
        if (translations[newLanguage]) {
            setLanguage(newLanguage);
        } else {
            console.warn(`Language "${newLanguage}" is not supported.`);
        }
    };

    const t = (key) => {
        const keys = key.split('.'); 
        let currentTranslation = translations[language]; 
        for (let i = 0; i < keys.length; i++) {
            if (currentTranslation && typeof currentTranslation === 'object' && keys[i] in currentTranslation) {
                currentTranslation = currentTranslation[keys[i]];
            } else {
                console.warn(`Translation missing for key: "${key}" in "${language}" language. Falling back to English.`);
                let englishTranslation = translations['en']; 
                for (let j = 0; j < keys.length; j++) {
                    if (englishTranslation && typeof englishTranslation === 'object' && keys[j] in englishTranslation) {
                        englishTranslation = englishTranslation[keys[j]];
                    } else {
                        console.error(`Translation not found for key: "${key}" in English.`);
                        return key; 
                    }
                }
                return englishTranslation;
            }
        }

       if (typeof currentTranslation === 'function') {
            return (...args) => currentTranslation(...args);
        }

        return currentTranslation; 
    };

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};